/* Math Quest — weekly school content.
   This file is the only thing that needs to change each week:
   spelling words, homework math problems, and topic quizzes, per kid.
   Kids are matched by their hero name (lower case). Anyone else gets the grade list. */

const GRADE3_WORDS = [
  { w: 'because', s: 'I wore my coat because it was cold outside.' },
  { w: 'friend', s: 'My friend and I built a fort.' },
  { w: 'again', s: 'Can we play that game again?' },
  { w: 'laugh', s: 'The funny puppy made me laugh.' },
  { w: 'answer', s: 'Raise your hand to answer the question.' },
  { w: 'believe', s: 'I believe you can do it.' },
  { w: 'different', s: 'Every snowflake is different.' },
  { w: 'enough', s: 'Do we have enough cookies for everyone?' },
  { w: 'favorite', s: 'Blue is my favorite color.' },
  { w: 'beautiful', s: 'The sunset was beautiful tonight.' },
  { w: 'caught', s: 'She caught the ball with one hand.' },
  { w: 'heard', s: 'I heard an owl hooting last night.' },
  { w: 'library', s: 'We borrowed three books from the library.' },
  { w: 'minute', s: 'Please wait one minute.' },
  { w: 'often', s: 'We often walk the dog after dinner.' },
  { w: 'people', s: 'Lots of people came to the fair.' },
  { w: 'busy', s: 'The bees are busy making honey.' },
  { w: 'early', s: 'We woke up early for the trip.' },
  { w: 'through', s: 'The train went through the tunnel.' },
  { w: 'surprise', s: 'We planned a surprise party for Mom.' }
];

const GRADE5_WORDS = [
  { w: 'necessary', s: 'Is it necessary to bring a jacket?' },
  { w: 'separate', s: 'Please separate the paper from the plastic.' },
  { w: 'environment', s: 'We should protect the environment.' },
  { w: 'government', s: 'The government builds roads and schools.' },
  { w: 'restaurant', s: 'We ate tacos at a new restaurant.' },
  { w: 'rhythm', s: 'Clap your hands to the rhythm of the song.' },
  { w: 'receive', s: 'Did you receive my letter?' },
  { w: 'immediately', s: 'Come inside immediately, it is starting to rain.' },
  { w: 'temperature', s: 'The temperature dropped below freezing.' },
  { w: 'calendar', s: 'Mark the game on the calendar.' },
  { w: 'opportunity', s: 'This is a great opportunity to learn.' },
  { w: 'similar', s: 'Your drawing is similar to mine.' },
  { w: 'recommend', s: 'I recommend the chocolate ice cream.' },
  { w: 'guarantee', s: 'I can not guarantee it will be sunny.' },
  { w: 'exaggerate', s: 'Do not exaggerate how big the fish was.' },
  { w: 'conscience', s: 'Her conscience told her to tell the truth.' },
  { w: 'particular', s: 'He likes one particular kind of cereal.' },
  { w: 'vacuum', s: 'Please vacuum the living room rug.' },
  { w: 'parallel', s: 'The two lines are parallel.' },
  { w: 'February', s: 'February is the shortest month.' }
];


// Jibreel: words from his Week 2 & Week 4 schoolwork (plurals he missed, unit vocabulary, spelling-check words)
const JIBREEL_WORDS = [
  { w: 'boxes', s: 'The store shipped the action figures in fourteen boxes.' },
  { w: 'brushes', s: 'Please wash the paint brushes after art.' },
  { w: 'dresses', s: 'The store had racks of colorful dresses.' },
  { w: 'babies', s: 'The babies were sleeping in the nursery.' },
  { w: 'benches', s: 'We sat on the benches at the park.' },
  { w: 'foxes', s: 'Two foxes ran across the field.' },
  { w: 'paragraphs', s: 'Write two paragraphs about your weekend.' },
  { w: 'loaves', s: 'The bakery made fifteen loaves of bread.' },
  { w: 'dollars', s: 'The lunchbox costs ten dollars.' },
  { w: 'pies', s: 'The bakeshop baked twenty-six blueberry pies.' },
  { w: 'equivalent', s: 'Four tenths is equivalent to forty hundredths.' },
  { w: 'fraction', s: 'Three fourths is a fraction.' },
  { w: 'volume', s: 'The volume of the box is eighty-four cubic units.' },
  { w: 'perimeter', s: 'Add all four sides to find the perimeter.' },
  { w: 'measure', s: 'Use a protractor to measure the angle.' },
  { w: 'acute', s: 'An acute angle is smaller than a right angle.' },
  { w: 'obtuse', s: 'An obtuse angle is bigger than a right angle.' },
  { w: 'multiplied', s: 'I multiplied four by six and got twenty-four.' },
  { w: 'honest', s: 'It is important to be honest.' },
  { w: 'view', s: 'The view from the mountain was amazing.' },
  { w: 'observe', s: 'Scientists observe animals in nature.' },
  { w: 'believable', s: 'His story was not very believable.' },
  { w: 'unidentified', s: 'An unidentified bird landed on the fence.' },
  { w: 'disconnected', s: 'The video call got disconnected.' }
];


// Mika: his Week 4 (long o) and Week 5 (u sounds) spelling lists, plus the bonus words
const MIKA_WORDS = [
  { w: 'rocket', s: 'The rocket zoomed up into space.' },
  { w: 'pocket', s: 'I keep my lucky rock in my pocket.' },
  { w: 'hold', s: 'Please hold my hand when we cross the street.' },
  { w: 'told', s: 'My teacher told us a funny story.' },
  { w: 'often', s: 'We often play soccer after school.' },
  { w: 'grow', s: 'Plants need water and sun to grow.' },
  { w: 'throne', s: 'The king sat on his golden throne.' },
  { w: 'so', s: 'I was so happy to see my friend.' },
  { w: 'sew', s: 'Grandma will sew a patch on my jeans.' },
  { w: 'most', s: 'Pizza is the food I like the most.' },
  { w: 'almost', s: 'I almost missed the bus this morning.' },
  { w: 'both', s: 'Both of my shoes are untied.' },
  { w: 'coach', s: 'The coach blew her whistle.' },
  { w: 'open', s: 'Please open the door for the dog.' },
  { w: 'also', s: 'I like cats, and I also like dogs.' },
  { w: 'under', s: 'The ball rolled under the couch.' },
  { w: 'such', s: 'That was such a cool magic trick.' },
  { w: 'much', s: 'How much does the toy cost?' },
  { w: 'young', s: 'The young puppy was learning to walk.' },
  { w: 'touch', s: 'Do not touch the hot stove.' },
  { w: 'use', s: 'You can use my pencil.' },
  { w: 'your', s: 'Is this your backpack?' },
  { w: 'you', s: 'Thank you for the present.' },
  { w: 'unit', s: 'We are learning a new unit in math.' },
  { w: 'cute', s: 'The baby bunny is so cute.' },
  { w: 'few', s: 'I have a few crayons left.' },
  { w: 'new', s: 'I got new shoes for school.' },
  { w: 'fuel', s: 'The rocket needs fuel to fly.' },
  { w: 'human', s: 'A human has two hands and two feet.' },
  { w: 'music', s: 'We dance when the music plays.' },
  { w: 'state', s: 'California is a big state.' },
  { w: 'country', s: 'The United States is our country.' },
  { w: 'California', s: 'We live in California.' }
];

// Word bank, grades 1-3 (240 words in packs of 20: long vowels, r-controlled, oi/ou, digraphs, silent letters, endings, compounds, tricky words). A new pack unlocks after 15 words of the last pack are learned.
const WORD_BANK_3 = [
  { w: 'cake', s: "We ate chocolate cake at the party." },
  { w: 'plate', s: "Put your sandwich on the plate." },
  { w: 'snake', s: "The green snake slid under a rock." },
  { w: 'grape', s: "I ate one purple grape." },
  { w: 'train', s: "The train blew its whistle." },
  { w: 'paint', s: "Let's paint a picture of the sea." },
  { w: 'rain', s: "The rain made puddles on the path." },
  { w: 'tail', s: "The puppy wagged its tail." },
  { w: 'play', s: "Can you come out to play?" },
  { w: 'stay', s: "We will stay at Grandma's house." },
  { w: 'today', s: "Today is a sunny day." },
  { w: 'away', s: "The bird flew away." },
  { w: 'gray', s: "The sky turned gray before the storm." },
  { w: 'brave', s: "The brave knight faced the dragon." },
  { w: 'chase', s: "Dogs love to chase balls." },
  { w: 'shade', s: "We sat in the shade of a tree." },
  { w: 'place', s: "This is my favorite place to read." },
  { w: 'space', s: "Astronauts travel into space." },
  { w: 'wait', s: "Please wait for your turn." },
  { w: 'afraid', s: "My little brother is afraid of the dark." },
  { w: 'sheep', s: "The sheep ate grass on the hill." },
  { w: 'green', s: "Frogs are often green." },
  { w: 'teeth', s: "Brush your teeth before bed." },
  { w: 'sleep', s: "Babies sleep a lot." },
  { w: 'queen', s: "The queen wore a shiny crown." },
  { w: 'beach', s: "We built a sandcastle at the beach." },
  { w: 'dream', s: "I had a dream about flying." },
  { w: 'clean', s: "Please clean up your toys." },
  { w: 'speak', s: "Speak loudly so everyone can hear." },
  { w: 'team', s: "Our team won the game." },
  { w: 'bright', s: "The sun is very bright today." },
  { w: 'night', s: "Owls hunt at night." },
  { w: 'light', s: "Turn on the light, please." },
  { w: 'high', s: "The kite flew high in the sky." },
  { w: 'tight', s: "These old shoes feel tight." },
  { w: 'smile', s: "Her smile made me happy." },
  { w: 'slide', s: "We went down the slide at the park." },
  { w: 'bike', s: "I ride my bike to school." },
  { w: 'shine', s: "The stars shine in the sky." },
  { w: 'tiger', s: "The tiger has orange and black stripes." },
  { w: 'float', s: "Leaves float on the pond." },
  { w: 'boat', s: "We rowed the boat across the lake." },
  { w: 'road', s: "Look both ways before you cross the road." },
  { w: 'toast', s: "I had toast with jam for breakfast." },
  { w: 'snow', s: "The snow covered the whole yard." },
  { w: 'slow', s: "The turtle is slow but steady." },
  { w: 'window', s: "Look out the window at the birds." },
  { w: 'yellow', s: "Bananas are yellow." },
  { w: 'stone', s: "I skipped a flat stone on the water." },
  { w: 'globe', s: "Find our state on the globe." },
  { w: 'bone', s: "The dog buried a bone." },
  { w: 'broke', s: "The vase broke when it fell." },
  { w: 'rule', s: "Always follow the class rule." },
  { w: 'flute', s: "She plays the flute in the band." },
  { w: 'blue', s: "The ocean looks blue." },
  { w: 'glue', s: "Use glue to stick the paper down." },
  { w: 'true', s: "Is that story true?" },
  { w: 'moon', s: "The moon is full tonight." },
  { w: 'spoon', s: "Eat your soup with a spoon." },
  { w: 'school', s: "We learn new things at school." },
  { w: 'farm', s: "Cows and pigs live on the farm." },
  { w: 'star', s: "Make a wish on a star." },
  { w: 'shark', s: "A shark swam near the boat." },
  { w: 'party', s: "We had a party for Grandpa." },
  { w: 'garden', s: "We grow tomatoes in our garden." },
  { w: 'storm', s: "The storm knocked down a tree." },
  { w: 'corn', s: "We ate corn on the cob." },
  { w: 'horse', s: "She rode a brown horse." },
  { w: 'morning', s: "I eat breakfast every morning." },
  { w: 'before', s: "Wash your hands before dinner." },
  { w: 'sister', s: "My sister likes to sing." },
  { w: 'winter', s: "It snows in the winter." },
  { w: 'letter', s: "I wrote a letter to my cousin." },
  { w: 'bird', s: "A bird built a nest in our tree." },
  { w: 'shirt', s: "He wore a red shirt." },
  { w: 'girl', s: "The girl kicked the ball." },
  { w: 'first', s: "I was first in line." },
  { w: 'turtle', s: "The turtle hid in its shell." },
  { w: 'purple', s: "Grapes can be purple." },
  { w: 'nurse', s: "The nurse helped me feel better." },
  { w: 'coin', s: "I found a coin on the sidewalk." },
  { w: 'point', s: "Point to the answer." },
  { w: 'noise', s: "What was that loud noise?" },
  { w: 'boil', s: "Wait for the water to boil." },
  { w: 'toy', s: "My favorite toy is a robot." },
  { w: 'enjoy', s: "I enjoy reading comics." },
  { w: 'loud', s: "The fireworks were very loud." },
  { w: 'cloud', s: "That cloud looks like a bunny." },
  { w: 'round', s: "A ball is round." },
  { w: 'mouth', s: "Open your mouth and say ah." },
  { w: 'house', s: "Our house has a red door." },
  { w: 'count', s: "Can you count to one hundred?" },
  { w: 'clown', s: "The clown had a big red nose." },
  { w: 'crown', s: "The king lost his crown." },
  { w: 'flower', s: "She picked a yellow flower." },
  { w: 'brown', s: "The bear has brown fur." },
  { w: 'straw', s: "I drink juice with a straw." },
  { w: 'draw', s: "Let's draw a map of the park." },
  { w: 'pause', s: "Pause the movie, please." },
  { w: 'sauce', s: "I like red sauce on my pasta." },
  { w: 'chair', s: "Sit in the chair by the window." },
  { w: 'cheese', s: "Mice like to eat cheese." },
  { w: 'lunch', s: "We eat lunch at noon." },
  { w: 'catch', s: "Can you catch the ball?" },
  { w: 'watch', s: "Let's watch the parade." },
  { w: 'ship', s: "The ship sailed across the sea." },
  { w: 'shell', s: "I found a pretty shell on the sand." },
  { w: 'wish', s: "Make a wish and blow out the candles." },
  { w: 'brush', s: "Brush your hair before school." },
  { w: 'think', s: "Think before you answer." },
  { w: 'three', s: "I have three pet fish." },
  { w: 'thank', s: "Remember to thank the bus driver." },
  { w: 'whale', s: "A whale is a huge animal." },
  { w: 'wheel', s: "The bike has a flat wheel." },
  { w: 'white', s: "Snow is white." },
  { w: 'phone', s: "Dad talked to Grandma on the phone." },
  { w: 'graph', s: "We made a graph of our favorite fruits." },
  { w: 'splash', s: "The kids splash in the pool." },
  { w: 'string', s: "Tie the string to the kite." },
  { w: 'spring', s: "Flowers bloom in the spring." },
  { w: 'knee', s: "I scraped my knee on the sidewalk." },
  { w: 'knock', s: "Knock on the door before you come in." },
  { w: 'know', s: "Do you know the answer?" },
  { w: 'knife', s: "Ask a grown-up to use the knife." },
  { w: 'write', s: "Write your name at the top." },
  { w: 'wrong', s: "Oops, I took a wrong turn." },
  { w: 'wrap', s: "Let's wrap the present in paper." },
  { w: 'lamb', s: "The lamb stayed close to its mother." },
  { w: 'climb', s: "Monkeys climb trees." },
  { w: 'comb', s: "Use a comb to fix your hair." },
  { w: 'thumb', s: "Give me a thumbs up with your thumb." },
  { w: 'city', s: "We visited a big city." },
  { w: 'circle', s: "Draw a circle on the paper." },
  { w: 'pencil', s: "Sharpen your pencil before the test." },
  { w: 'dance', s: "Let's dance to the music." },
  { w: 'giant', s: "The giant lived in a castle in the clouds." },
  { w: 'gentle', s: "Be gentle with the kitten." },
  { w: 'large', s: "An elephant is very large." },
  { w: 'cage', s: "The bird sat in its cage." },
  { w: 'bridge', s: "We walked across the bridge." },
  { w: 'jumped', s: "The frog jumped into the pond." },
  { w: 'planted', s: "We planted seeds in the spring." },
  { w: 'smiled', s: "She smiled at her friend." },
  { w: 'stopped', s: "The bus stopped at the corner." },
  { w: 'hopping', s: "The bunny is hopping across the grass." },
  { w: 'running', s: "The kids are running at recess." },
  { w: 'making', s: "Mom is making pancakes." },
  { w: 'swimming', s: "We went swimming in the lake." },
  { w: 'dishes', s: "I help wash the dishes." },
  { w: 'lunches', s: "We packed our lunches for the trip." },
  { w: 'puppies', s: "The puppies played in the yard." },
  { w: 'stories', s: "Grandpa tells funny stories." },
  { w: 'leaves', s: "The leaves fall in autumn." },
  { w: 'wolves', s: "The wolves howled at the moon." },
  { w: 'mice', s: "Two mice ran under the fridge." },
  { w: 'children', s: "The children sang a song." },
  { w: 'feet', s: "I have two feet." },
  { w: 'geese', s: "The geese flew south for the winter." },
  { w: 'cried', s: "The baby cried when it was hungry." },
  { w: 'tried', s: "I tried my best on the test." },
  { w: 'sunshine', s: "The sunshine felt warm on my face." },
  { w: 'rainbow', s: "We saw a rainbow after the rain." },
  { w: 'bedroom', s: "My bedroom has blue walls." },
  { w: 'homework', s: "I finished my homework after dinner." },
  { w: 'football', s: "We played football at the park." },
  { w: 'cupcake', s: "I had a cupcake with sprinkles." },
  { w: 'backpack', s: "Put your books in your backpack." },
  { w: 'playground', s: "We met at the playground." },
  { w: 'helpful', s: "Thank you for being so helpful." },
  { w: 'careful', s: "Be careful on the icy steps." },
  { w: 'hopeful', s: "I am hopeful it will be sunny." },
  { w: 'useless', s: "A broken umbrella is useless." },
  { w: 'slowly', s: "The snail moved slowly." },
  { w: 'quickly', s: "The rabbit ran quickly." },
  { w: 'kindness', s: "Show kindness to everyone." },
  { w: 'unlock', s: "Use the key to unlock the door." },
  { w: 'unhappy', s: "The kitten was unhappy in the rain." },
  { w: 'redo', s: "I had to redo my messy drawing." },
  { w: 'replay', s: "Can we replay that level?" },
  { w: 'darkness', s: "The cat can see in the darkness." },
  { w: 'brought', s: "I brought my lunch from home." },
  { w: 'thought', s: "I thought about my answer." },
  { w: 'bought', s: "Mom bought milk at the store." },
  { w: 'would', s: "Would you like some water?" },
  { w: 'could', s: "Could you help me carry this?" },
  { w: 'should', s: "You should wear a helmet." },
  { w: 'above', s: "The plane flew above the clouds." },
  { w: 'special', s: "Today is a special day." },
  { w: 'quiet', s: "Please be quiet in the library." },
  { w: 'quite', s: "The puzzle was quite hard." },
  { w: 'sure', s: "Are you sure you locked the door?" },
  { w: 'straight', s: "Draw a straight line with a ruler." },
  { w: 'color', s: "What color is your bike?" },
  { w: 'ocean', s: "Whales live in the ocean." },
  { w: 'together', s: "We built the fort together." },
  { w: 'tomorrow', s: "We will go to the zoo tomorrow." },
  { w: 'second', s: "I came in second in the race." },
  { w: 'sugar', s: "Cookies have a lot of sugar." },
  { w: 'island', s: "The pirates sailed to an island." },
  { w: 'family', s: "My family eats dinner together." },
  { w: 'animal', s: "The giraffe is a tall animal." },
  { w: 'around', s: "We walked around the lake." },
  { w: 'another', s: "Can I have another turn?" },
  { w: 'remember', s: "Remember to feed the fish." },
  { w: 'important', s: "It is important to be kind." },
  { w: 'picture', s: "I drew a picture of my dog." },
  { w: 'elephant', s: "The elephant has a long trunk." },
  { w: 'dinosaur', s: "The dinosaur bones are in the museum." },
  { w: 'kitchen', s: "Dad is cooking in the kitchen." },
  { w: 'mountain', s: "We hiked up the mountain." },
  { w: 'balloon', s: "The red balloon floated away." },
  { w: 'blanket', s: "I have a warm blanket on my bed." },
  { w: 'button', s: "Press the button to start." },
  { w: 'carrot', s: "The rabbit ate a carrot." },
  { w: 'dragon', s: "The dragon breathed fire." },
  { w: 'feather', s: "The bird dropped a feather." },
  { w: 'jacket', s: "Zip up your jacket." },
  { w: 'ladder', s: "Dad climbed the ladder to fix the roof." },
  { w: 'magnet', s: "The magnet sticks to the fridge." },
  { w: 'pillow', s: "I rest my head on a soft pillow." },
  { w: 'puzzle', s: "We finished a big puzzle." },
  { w: 'rabbit', s: "The rabbit hopped into its hole." },
  { w: 'silver', s: "The spoon is made of silver." },
  { w: 'sandwich', s: "I had a turkey sandwich." },
  { w: 'visit', s: "We visit our cousins in the summer." },
  { w: 'wagon', s: "I pulled my sister in the wagon." },
  { w: 'travel', s: "We travel by car to the lake." },
  { w: 'napkin', s: "Wipe your mouth with a napkin." },
  { w: 'hammer', s: "Use a hammer to hit the nail." },
  { w: 'monkey', s: "The monkey swung from the tree." },
  { w: 'pumpkin', s: "We carved a pumpkin." },
  { w: 'kitten', s: "The kitten chased a ball of yarn." },
  { w: 'basket', s: "Put the apples in the basket." },
  { w: 'market', s: "We bought fruit at the market." },
  { w: 'number', s: "Pick a number from one to ten." },
  { w: 'happen', s: "What will happen next in the story?" },
  { w: 'problem', s: "Can you solve this math problem?" },
  { w: 'insect', s: "An ant is an insect." },
  { w: 'planet', s: "Earth is our planet." },
  { w: 'seven', s: "A week has seven days." }
];

// Word bank, grades 4+ (240 words in packs of 20: -tion/-sion, suffixes, prefixes, doubling and plurals, ie/ei, silent letters, science and math vocabulary, challenge words).
const WORD_BANK_5 = [
  { w: 'action', s: "The movie was full of action." },
  { w: 'attention', s: "Please pay attention to the directions." },
  { w: 'direction', s: "Which direction is north?" },
  { w: 'education', s: "A good education opens many doors." },
  { w: 'invention', s: "The light bulb was an amazing invention." },
  { w: 'location', s: "Mark the location of the treasure on the map." },
  { w: 'population', s: "The population of our town is growing." },
  { w: 'celebration', s: "We had a celebration for my grandma's birthday." },
  { w: 'information', s: "The website has information about volcanoes." },
  { w: 'collection', s: "He has a huge rock collection." },
  { w: 'decision', s: "Choosing a pet was a big decision." },
  { w: 'division', s: "We practiced long division in class." },
  { w: 'explosion', s: "The volcano erupted with a loud explosion." },
  { w: 'television', s: "We watched the game on television." },
  { w: 'vision', s: "Glasses help improve your vision." },
  { w: 'confusion', s: "There was some confusion about the time." },
  { w: 'permission', s: "Ask for permission before you leave." },
  { w: 'discussion', s: "We had a discussion about the book." },
  { w: 'expression', s: "Her expression showed she was surprised." },
  { w: 'competition', s: "The skating competition is on Saturday." },
  { w: 'dangerous', s: "Crossing the ice is dangerous." },
  { w: 'famous', s: "The famous singer waved to the crowd." },
  { w: 'nervous', s: "I felt nervous before my performance." },
  { w: 'enormous', s: "The blue whale is enormous." },
  { w: 'curious', s: "The curious cat opened the cabinet." },
  { w: 'generous', s: "It was generous of you to share." },
  { w: 'delicious', s: "This soup is delicious." },
  { w: 'wonderful', s: "We had a wonderful time at the beach." },
  { w: 'graceful', s: "The skater made a graceful spin." },
  { w: 'powerful', s: "The engine is very powerful." },
  { w: 'fearless', s: "The fearless climber reached the top." },
  { w: 'careless', s: "A careless mistake cost us a point." },
  { w: 'happiness', s: "The puppy brought us so much happiness." },
  { w: 'weakness', s: "Everyone has a strength and a weakness." },
  { w: 'excitement', s: "The kids could not hide their excitement." },
  { w: 'agreement', s: "We came to an agreement about chores." },
  { w: 'movement', s: "The dancer's movement was smooth." },
  { w: 'equipment', s: "Put the sports equipment back in the shed." },
  { w: 'settlement', s: "The early settlement was near the river." },
  { w: 'loneliness', s: "The new puppy cured his loneliness." },
  { w: 'comfortable', s: "This couch is very comfortable." },
  { w: 'valuable', s: "The old coin is valuable." },
  { w: 'available', s: "Is this seat available?" },
  { w: 'reasonable', s: "That price seems reasonable." },
  { w: 'remarkable', s: "She made a remarkable recovery." },
  { w: 'possible', s: "Anything is possible if you practice." },
  { w: 'terrible', s: "The storm caused terrible damage." },
  { w: 'visible', s: "The mountain was visible from far away." },
  { w: 'incredible', s: "The view from the top was incredible." },
  { w: 'responsible', s: "You are responsible for feeding the dog." },
  { w: 'distance', s: "We measured the distance to the lake." },
  { w: 'balance', s: "Skaters need good balance." },
  { w: 'appearance', s: "The magician made a sudden appearance." },
  { w: 'performance', s: "Her performance got a standing ovation." },
  { w: 'difference', s: "Can you tell the difference between the twins?" },
  { w: 'evidence', s: "The detective looked for evidence." },
  { w: 'patience', s: "Fishing takes a lot of patience." },
  { w: 'confidence', s: "Practice gives you confidence." },
  { w: 'audience', s: "The audience clapped loudly." },
  { w: 'science', s: "We did an experiment in science class." },
  { w: 'disagree', s: "It is okay to disagree politely." },
  { w: 'disappear', s: "The magician made the coin disappear." },
  { w: 'dishonest', s: "It is dishonest to cheat on a test." },
  { w: 'misunderstand', s: "Please do not misunderstand me." },
  { w: 'mistake', s: "Everyone makes a mistake sometimes." },
  { w: 'misspell', s: "Try not to misspell your name." },
  { w: 'prehistoric', s: "Dinosaurs lived in prehistoric times." },
  { w: 'preview', s: "We watched a preview of the new movie." },
  { w: 'rebuild', s: "They will rebuild the old bridge." },
  { w: 'unusual', s: "It is unusual to see snow in May." },
  { w: 'unknown', s: "The island was unknown to the explorers." },
  { w: 'impossible', s: "Nothing is impossible if you try hard." },
  { w: 'impatient', s: "The impatient driver honked the horn." },
  { w: 'incorrect', s: "That answer is incorrect, try again." },
  { w: 'invisible', s: "The superhero became invisible." },
  { w: 'irregular', s: "The rock had an irregular shape." },
  { w: 'nonfiction', s: "A nonfiction book tells true facts." },
  { w: 'overcome', s: "She worked hard to overcome her fear." },
  { w: 'underground', s: "Moles dig tunnels underground." },
  { w: 'international', s: "The airport has international flights." },
  { w: 'beginning', s: "The beginning of the book was exciting." },
  { w: 'forgotten', s: "I had forgotten my lunch at home." },
  { w: 'admitted', s: "He admitted that he broke the vase." },
  { w: 'controlled', s: "The pilot controlled the plane carefully." },
  { w: 'occurred', s: "The accident occurred last night." },
  { w: 'preferred', s: "She preferred skating to swimming." },
  { w: 'happiest', s: "That was the happiest day of my life." },
  { w: 'heavier', s: "The bowling ball is heavier than the soccer ball." },
  { w: 'carried', s: "He carried the groceries inside." },
  { w: 'worried', s: "Mom was worried when I was late." },
  { w: 'studied', s: "I studied my spelling words." },
  { w: 'replied', s: "She replied to my letter right away." },
  { w: 'families', s: "Many families came to the picnic." },
  { w: 'countries', s: "We learned about countries in Africa." },
  { w: 'activities', s: "The camp has lots of fun activities." },
  { w: 'knives', s: "Be careful with the sharp knives." },
  { w: 'shelves', s: "The library shelves are full of books." },
  { w: 'halves', s: "Cut the apple into two halves." },
  { w: 'potatoes', s: "We mashed the potatoes for dinner." },
  { w: 'echoes', s: "Our voices made echoes in the cave." },
  { w: 'achieve', s: "You can achieve your goals with hard work." },
  { w: 'niece', s: "My aunt brought her niece to the party." },
  { w: 'shield', s: "The knight raised his shield." },
  { w: 'field', s: "The horses ran across the field." },
  { w: 'ceiling', s: "A spider crawled across the ceiling." },
  { w: 'neighbor', s: "Our neighbor has a friendly dog." },
  { w: 'receipt', s: "Keep the receipt in case you return it." },
  { w: 'foreign', s: "She speaks a foreign language." },
  { w: 'height', s: "We measured the height of the tree." },
  { w: 'knowledge', s: "Reading gives you knowledge." },
  { w: 'knuckle', s: "I bumped my knuckle on the door." },
  { w: 'wrestle', s: "The bear cubs like to wrestle." },
  { w: 'whistle', s: "The coach blew the whistle." },
  { w: 'castle', s: "The castle had tall stone towers." },
  { w: 'listen', s: "Listen carefully to the directions." },
  { w: 'autumn', s: "The leaves turn orange in autumn." },
  { w: 'column', s: "Add the numbers in each column." },
  { w: 'doubt', s: "I have no doubt that you can do it." },
  { w: 'design', s: "She will design a new logo." },
  { w: 'solemn', s: "The ceremony was quiet and solemn." },
  { w: 'experiment', s: "Our experiment showed that plants need light." },
  { w: 'hypothesis', s: "Write your hypothesis before the experiment." },
  { w: 'predict', s: "Can you predict what will happen next?" },
  { w: 'conclusion', s: "What conclusion can you draw from the data?" },
  { w: 'energy', s: "The sun gives us energy." },
  { w: 'gravity', s: "Gravity pulls things toward the ground." },
  { w: 'magnetic', s: "The compass needle is magnetic." },
  { w: 'molecule', s: "A water molecule is very tiny." },
  { w: 'organism', s: "A tiny organism lives in pond water." },
  { w: 'habitat', s: "The desert is the camel's habitat." },
  { w: 'climate', s: "The climate in Alaska is cold." },
  { w: 'erosion', s: "Wind and water cause erosion." },
  { w: 'fossil', s: "We found a fossil of a seashell." },
  { w: 'volcano', s: "Lava poured out of the volcano." },
  { w: 'atmosphere', s: "The atmosphere surrounds our planet." },
  { w: 'liquid', s: "Water is a liquid." },
  { w: 'oxygen', s: "We need oxygen to breathe." },
  { w: 'nutrient', s: "Calcium is a nutrient that builds strong bones." },
  { w: 'ecosystem', s: "A pond is a small ecosystem." },
  { w: 'constellation', s: "The Big Dipper is a famous constellation." },
  { w: 'addition', s: "Addition means putting numbers together." },
  { w: 'subtraction', s: "Subtraction means taking away." },
  { w: 'multiply', s: "Multiply six by seven." },
  { w: 'divide', s: "Divide the cookies equally among friends." },
  { w: 'decimal', s: "Put the decimal point in the right place." },
  { w: 'numerator', s: "The numerator is the top number of a fraction." },
  { w: 'denominator', s: "The denominator is the bottom number of a fraction." },
  { w: 'equation', s: "Solve the equation to find the answer." },
  { w: 'estimate', s: "Estimate how many jellybeans are in the jar." },
  { w: 'pattern', s: "Can you find the pattern in these numbers?" },
  { w: 'product', s: "The product of three and four is twelve." },
  { w: 'quotient', s: "The quotient of twenty divided by five is four." },
  { w: 'remainder', s: "Seventeen divided by five has a remainder of two." },
  { w: 'triangle', s: "A triangle has three sides." },
  { w: 'rectangle', s: "A rectangle has four right angles." },
  { w: 'diameter', s: "Measure the diameter of the circle." },
  { w: 'symmetry', s: "A butterfly has symmetry." },
  { w: 'vertical', s: "Draw a vertical line down the page." },
  { w: 'horizontal', s: "The horizon is a horizontal line." },
  { w: 'angle', s: "A right angle looks like the corner of a book." },
  { w: 'although', s: "Although it rained, we still had fun." },
  { w: 'anxious', s: "I was anxious about the big test." },
  { w: 'awkward', s: "There was an awkward silence." },
  { w: 'bruise', s: "I got a bruise when I fell." },
  { w: 'business', s: "My uncle owns a small business." },
  { w: 'committee', s: "The committee planned the school fair." },
  { w: 'definitely', s: "I will definitely come to your party." },
  { w: 'embarrass', s: "Please do not embarrass me in front of my friends." },
  { w: 'especially', s: "I love fruit, especially strawberries." },
  { w: 'excellent', s: "You did an excellent job." },
  { w: 'familiar', s: "That song sounds familiar." },
  { w: 'frequently', s: "We frequently visit the library." },
  { w: 'gorgeous', s: "The sunset was gorgeous." },
  { w: 'humorous', s: "The book was humorous and made me laugh." },
  { w: 'independent', s: "She is very independent and likes to do things herself." },
  { w: 'interrupt', s: "Please do not interrupt when someone is talking." },
  { w: 'jewelry', s: "Grandma keeps her jewelry in a box." },
  { w: 'laboratory', s: "The scientist worked in a laboratory." },
  { w: 'leisure', s: "Reading is my favorite leisure activity." },
  { w: 'license', s: "You need a license to drive a car." },
  { w: 'mysterious', s: "A mysterious sound came from the attic." },
  { w: 'occasion', s: "A wedding is a special occasion." },
  { w: 'original', s: "That is a very original idea." },
  { w: 'physical', s: "Physical exercise keeps you healthy." },
  { w: 'privilege', s: "It is a privilege to lead the team." },
  { w: 'recognize', s: "I did not recognize you with your new haircut." },
  { w: 'relief', s: "It was a relief to find my lost dog." },
  { w: 'rhyme', s: "Cat and hat rhyme." },
  { w: 'schedule', s: "Check the schedule for practice times." },
  { w: 'scissors', s: "Cut the paper with scissors." },
  { w: 'sincerely', s: "End your letter with sincerely." },
  { w: 'souvenir', s: "I bought a souvenir at the museum." },
  { w: 'sufficient', s: "We have sufficient food for the trip." },
  { w: 'thorough', s: "Give the room a thorough cleaning." },
  { w: 'tongue', s: "The frog caught a fly with its tongue." },
  { w: 'twelfth', s: "My twelfth birthday is next year." },
  { w: 'unique', s: "Every snowflake is unique." },
  { w: 'usually', s: "I usually walk to school." },
  { w: 'vegetable', s: "Broccoli is my favorite vegetable." },
  { w: 'yacht', s: "The yacht sailed across the bay." },
  { w: 'adventure', s: "Our camping trip was a real adventure." },
  { w: 'apologize', s: "I want to apologize for being late." },
  { w: 'athlete', s: "A skater is a strong athlete." },
  { w: 'bicycle', s: "I rode my bicycle to the park." },
  { w: 'boundary', s: "The river forms the boundary between the towns." },
  { w: 'calculate', s: "Calculate the total cost of the snacks." },
  { w: 'character', s: "Who is your favorite character in the book?" },
  { w: 'chocolate', s: "I love chocolate ice cream." },
  { w: 'citizen', s: "A good citizen helps the community." },
  { w: 'community', s: "Our community planted trees in the park." },
  { w: 'courage', s: "It takes courage to try something new." },
  { w: 'customer', s: "The customer paid for her groceries." },
  { w: 'describe', s: "Describe your favorite place." },
  { w: 'dictionary', s: "Look up the word in the dictionary." },
  { w: 'emergency', s: "Call for help in an emergency." },
  { w: 'exercise', s: "Exercise makes your heart strong." },
  { w: 'explanation', s: "The teacher gave a clear explanation." },
  { w: 'festival', s: "We went to a music festival." },
  { w: 'hospital', s: "The doctor works at the hospital." },
  { w: 'instrument', s: "The violin is a string instrument." },
  { w: 'journey', s: "The journey took three days." },
  { w: 'language', s: "She can speak more than one language." },
  { w: 'machine', s: "The machine makes ice cream." },
  { w: 'material', s: "Cotton is a soft material." },
  { w: 'message', s: "I left a message for my friend." },
  { w: 'minimum', s: "You need a minimum of four players." },
  { w: 'musician', s: "The musician played the guitar." },
  { w: 'ordinary', s: "It was just an ordinary day." },
  { w: 'paragraph', s: "Write one paragraph about your pet." },
  { w: 'president', s: "The class elected a new president." },
  { w: 'probably', s: "It will probably rain tomorrow." },
  { w: 'quarter', s: "A quarter is worth twenty-five cents." },
  { w: 'recycle', s: "We recycle cans and bottles." },
  { w: 'signature', s: "Put your signature at the bottom." },
  { w: 'skeleton', s: "The skeleton holds up your body." },
  { w: 'suggestion', s: "Do you have a suggestion for the name?" },
  { w: 'surface', s: "The surface of the lake was calm." },
  { w: 'tournament', s: "Our team won the soccer tournament." },
  { w: 'universe', s: "The universe is full of stars." },
  { w: 'vocabulary', s: "Reading helps build your vocabulary." }
];

window.MQ_CONTENT = {
  wordBank: { '3': WORD_BANK_3, '5': WORD_BANK_5 },
  updated: '2026-09-26',

  kids: {
    mika: {
      spelling: { title: "Mika's words from school (Week 4 & 5)", words: MIKA_WORDS },
      homework: [
        { id: 'm-wk5-review', title: 'Groups, Arrays & Graphs Review', problems: [
          { q: 'Jason has 6 bookshelves. There are 6 books on each shelf. How many books?', a: '36' },
          { q: 'Madison makes 4 types of ribbon. Each type comes in 3 colors. How many ribbons?', a: '12', hint: '4 groups of 3: 3, 6, 9, 12.' },
          { q: 'A hexagon uses 6 straws. How many straws for 3 hexagons?', a: '18' },
          { q: 'Elvira bought 4 packages of stickers with 6 in each. How many stickers?', a: '24' },
          { q: 'James got 3 hits in each game. He played 4 games. How many hits?', a: '12', hint: '4 games × 3 hits. Count by 3s four times.' },
          { q: 'Mrs. Burns buys 5 boxes with 6 muffins in each. How many muffins?', a: '30' },
          { q: '5 × 6 = ?', a: '30', hint: 'Count by 5s six times: 5, 10, 15, 20, 25, 30.' },
          { q: '9 × 6 = ?', a: '54', hint: '9 × 3 = 27. Double it!' },
          { q: '6 × 4 = ?', a: '24', hint: '3 × 4 = 12. Double it!' },
          { q: '7 × 3 = ?', a: '21', hint: '7 + 7 + 7' },
          { q: '6 × 7 = ?', a: '42', hint: '3 × 7 = 21. Double it!' },
          { q: '3 × 6 = ?', a: '18' },
          { q: '30 people are going on a trip. 5 people fit in each car. How many cars?', a: '6', hint: 'We want the number of CARS. Count by 5s to 30: 5, 10, 15, 20, 25, 30.' },
          { q: '24 buttons go into 3 equal piles. How many in each pile?', a: '8', hint: '3 × ? = 24' },
          { q: '36 party favors on 9 tables, the same on each. How many on each table?', a: '4', hint: '9 × ? = 36' },
          { q: '28 chairs in rows of 7. How many rows?', a: '4', hint: 'Count by 7s: 7, 14, 21, 28.' },
          { q: 'Make 6 jumps of 3 on a number line. Where do you land?', a: '18' },
          { q: 'A picture graph key says each star = 2 votes. Pizza has 4 stars. How many votes?', a: '8', hint: 'Count by 2s for each star.' }
        ] }
      ],
      quizzes: ['m-reading', 'm-math', 'ca-missions']
    },
    jibreel: {
      spelling: { title: "Jibreel's words from school (Week 2 & 4)", words: JIBREEL_WORDS },
      homework: [
        { id: 'j-wk4-review', title: 'Week 2 & 4 Review', problems: [
          { q: '112 people are coming to a party. Each table seats 7. How many tables?', a: '16' },
          { q: '136 flowers, 8 flowers in each vase. How many vases?', a: '17' },
          { q: 'Aiden read 182 minutes in 7 days, the same each night. Minutes per night?', a: '26', hint: 'Check your answer: 25 × 7 = 175, not 182. Try one more.' },
          { q: 'A backpack costs $49. A lunchbox costs $7. How many TIMES as much is the backpack?', a: '7', hint: 'The answer is a number of times, not dollars. 49 ÷ 7.' },
          { q: '86 cups of pecans. 2 cups make one pie. How many pies?', a: '43' },
          { q: '4/10 + ?/100 = 78/100. What is the missing fraction?', a: '38/100', hint: '4/10 is the same as 40/100.' },
          { q: '7/10 + ?/100 = 94/100. What is the missing fraction?', a: '24/100', hint: '7/10 is the same as 70/100.' },
          { q: 'A room is 9 feet wide. It is 4 times as long as it is wide. Perimeter in feet?', a: '90', hint: 'Length = 9 × 4 = 36. Then add ALL 4 sides.' },
          { q: 'A pool is 10 feet wide. It is 3 times as long as it is wide. Perimeter in feet?', a: '80', hint: 'Length = 30. Add all 4 sides.' },
          { q: 'A building is 14 feet wide. It is 6 times as long as it is wide. Perimeter in feet?', a: '196' },
          { q: 'A rectangle has a perimeter of 50 feet. The length is 18 feet. Width?', a: '7', hint: '50 − 18 − 18 = 14 for both widths.' },
          { q: 'A rectangle has an area of 56 sq. ft. The length is 14 feet. Width?', a: '4', hint: '14 × ? = 56' },
          { q: 'What is the value of the 6 in 657,224?', a: '600000' },
          { q: '16 tens + 3 hundreds = ?', a: '460' },
          { q: 'Heather can do 8 pushups. Her brother can do 6 times as many. How many can he do?', a: '48' },
          { q: 'A cube-shaped box is 7 inches deep. What is its volume in cubic inches?', a: '343', hint: 'A cube is 7 × 7 × 7.' },
          { q: '8 × 3 × 10 = ?', a: '240' },
          { q: 'A box is 4 units long, 2 units wide and 15 units tall. Volume?', a: '120' }
        ] }
      ],
      quizzes: ['j-grammar', 'j-volume', 'ca-missions']
    }
  },

  // Players who aren't named above get a list by grade.
  byGrade: {
    '3': { spelling: { title: 'Starter 3rd grade words', words: GRADE3_WORDS }, homework: [], quizzes: ['ca-missions'] },
    '5': { spelling: { title: 'Starter 5th grade words', words: GRADE5_WORDS }, homework: [], quizzes: ['ca-missions'] }
  },

  quizzes: {
    'm-reading': {
      title: 'Reading & Grammar Power-Up',
      emoji: '📖',
      note: "From Mika's Week 3-5 worksheets",
      questions: [
        { q: 'What is the lesson at the end of a fable called?', c: ['The title', 'The moral', 'The setting', 'The author'], a: 1, why: 'A fable ends with a moral, a lesson about how to act.' },
        { q: 'Which is NOT usually part of a fable?', c: ['Animals that talk', 'A lesson or moral', 'A problem to solve', 'A map of a real city'], a: 3, why: 'Fables have talking animals, a problem and a moral. They do not need real maps.' },
        { q: 'In "The Fox and the Crow," the fox tricks the crow. What word describes the fox?', c: ['Clever', 'Sleepy', 'Shy', 'Honest'], a: 0, why: 'The fox is clever and sly. He uses sweet words to trick the crow.' },
        { q: 'The crow believes she is the most beautiful bird. What word describes the crow?', c: ['Brave', 'Vain', 'Kind', 'Tired'], a: 1, why: 'Vain means thinking too much about how great you look.' },
        { q: 'Which is a SENSORY detail (uses the five senses)?', c: ['The bread smelled warm and sweet.', 'The story has three parts.', 'It was a Tuesday.', 'Sam is in third grade.'], a: 0, why: 'Smell is one of the five senses: see, hear, smell, taste, touch.' },
        { q: 'How many syllables are in "rocket"?', c: ['1', '2', '3', '4'], a: 1, why: 'Clap it: rock-et. Two claps, two syllables.' },
        { q: 'How many syllables are in "grow"?', c: ['1', '2', '3', '4'], a: 0, why: 'Clap it: grow. One clap.' },
        { q: 'Which word has the long o sound spelled "oa"?', c: ['coach', 'told', 'grow', 'throne'], a: 0, why: 'c-OA-ch. The o and a team up to say "oh".' },
        { q: 'Which is spelled correctly?', c: ['almost', 'amolst', 'allmost', 'almoast'], a: 0, why: 'al + most = almost.' },
        { q: 'Which is spelled correctly?', c: ['sowe', 'sew', 'soe', 'sewe'], a: 1, why: '"Sew" (like sewing a shirt) is spelled s-e-w, but says "so".' },
        { q: 'Which book title is capitalized correctly?', c: ['Beauty And The Beast', 'beauty and the beast', 'Beauty and the Beast', 'Beauty and The beast'], a: 2, why: 'Capitalize the first word, the last word and big words. Little words like "and" and "the" stay small in the middle.' },
        { q: 'Which title is capitalized correctly?', c: ['The Wizard of Oz', 'The Wizard Of Oz', 'the wizard of oz', 'The wizard of Oz'], a: 0, why: '"of" is a short word in the middle, so it stays lowercase.' },
        { q: 'Choose the right verb: "Marissa ___ the piano very well."', c: ['play', 'plays'], a: 1, why: 'Marissa is ONE person, so the verb gets an -s: plays.' },
        { q: 'Choose the right verb: "My friends ___ in the chorus."', c: ['sing', 'sings'], a: 0, why: 'Friends is MORE than one, so no -s: sing.' },
        { q: 'Which word is a synonym (same meaning) for "smart"?', c: ['excited', 'intelligent', 'miserable'], a: 1, why: 'Smart and intelligent mean the same thing.' },
        { q: 'Which word is an antonym (opposite) of "funny"?', c: ['serious', 'hilarious', 'hysterical'], a: 0, why: 'Funny is the opposite of serious. Hilarious means VERY funny.' },
        { q: 'Which word means "without care"?', c: ['careful', 'carest', 'careless'], a: 2, why: 'The ending -less means "without". Careless = without care.' },
        { q: 'Which word means "to do again"?', c: ['predo', 'redo', 'undo'], a: 1, why: 'The prefix re- means "again". Redo = do again.' },
        { q: 'What root do "telegraph" and "photograph" share?', c: ['tele', 'photo', 'graph', 'ph'], a: 2, why: 'Graph means write or draw. Both words end in graph.' },
        { q: 'Which is a synonym for "hungry"?', c: ['stuffed', 'starving', 'satisfied'], a: 1, why: 'Starving means VERY hungry. Stuffed and satisfied mean full.' }
      ]
    },
    'm-math': {
      title: 'Groups & Graphs Quiz',
      emoji: '📊',
      note: "From Mika's 3rd grade math pages",
      questions: [
        { q: '30 people, 5 in each car. Which number sentence finds how many cars?', c: ['30 × 5', '30 ÷ 5', '30 + 5', '30 − 5'], a: 1, why: 'We know the total and the size of each group, so we divide: 30 ÷ 5 = 6 cars.' },
        { q: '3 rows of 4 stars. Which number sentence matches?', c: ['3 + 4', '3 × 4', '4 − 3', '12 ÷ 4 = 4'], a: 1, why: 'Rows × how many in each row: 3 × 4 = 12.' },
        { q: 'On a number line, 6 × 3 means...', c: ['3 jumps of 6', '6 jumps of 3', '9 jumps of 1', '6 jumps of 6'], a: 1, why: 'The first number is how many jumps. The second is how big each jump is.' },
        { q: 'A picture graph key says each 😀 = 2. How many is 😀😀😀?', c: ['3', '5', '6', '9'], a: 2, why: 'Count by 2s: 2, 4, 6.' },
        { q: 'A key says each ⭐ = 2. What is half a ⭐ worth?', c: ['1', '2', '4', '0'], a: 0, why: 'Half of 2 is 1.' },
        { q: 'A bar graph counts by 2s. A bar stops halfway between 6 and 8. What number is that?', c: ['6', '7', '8', '9'], a: 1, why: 'Halfway between 6 and 8 is 7.' },
        { q: 'Apples got 8 votes and Grapes got 3. How many MORE for Apples?', c: ['11', '5', '24', '3'], a: 1, why: '"How many more" means subtract: 8 − 3 = 5.' },
        { q: 'Which fact helps you find 6 × 7?', c: ['3 × 7, then double it', '6 + 7', '7 − 6', '6 × 6 − 1'], a: 0, why: '6 is double 3. 3 × 7 = 21, double 21 = 42.' },
        { q: '9 × 6 = ?', c: ['45', '54', '56', '63'], a: 1, why: '9 × 3 = 27, double it = 54.' },
        { q: '24 buttons in 3 equal piles. How many in each pile?', c: ['6', '7', '8', '21'], a: 2, why: '3 × 8 = 24, so 24 ÷ 3 = 8.' },
        { q: 'Which is an ARRAY?', c: ['Things in neat rows and columns', 'A pile of things', 'A circle of things', 'Things in a line with gaps'], a: 0, why: 'An array has equal rows, like eggs in a carton.' },
        { q: 'Which multiplication matches 7 + 7 + 7?', c: ['7 × 7', '3 × 7', '7 + 3', '21 × 3'], a: 1, why: 'Three groups of 7 is 3 × 7 = 21.' }
      ]
    },
    'j-grammar': {
      title: 'Grammar Power-Up',
      emoji: '✏️',
      note: "From Jibreel's Week 2 & 4 worksheets",
      questions: [
        { q: 'What is the plural of "baby"?', c: ['babys', 'babies', 'babyes', 'babbies'], a: 1, why: 'When a word ends in a consonant + y, change the y to i and add -es: babies.' },
        { q: 'What is the plural of "loaf"?', c: ['loafs', 'loaves', 'loafes', 'loavs'], a: 1, why: 'Many words ending in -f change the f to v and add -es: loaf → loaves.' },
        { q: 'What is the plural of "paragraph"?', c: ['paragraph', 'paragraphes', 'paragraphs', 'paragraphies'], a: 2, why: 'Just add -s: paragraphs.' },
        { q: 'What is the plural of "bench"?', c: ['benchs', 'benches', 'benchies', 'bench'], a: 1, why: 'Words ending in -ch, -sh, -s, -x or -z add -es: benches.' },
        { q: 'What is the root word of "mistreat"?', c: ['mis', 'treat', 'mistr', 'eat'], a: 1, why: '"Mis-" is a prefix. The root word is "treat."' },
        { q: 'What is the root word of "reopened"?', c: ['re', 'open', 'ope', 'opened'], a: 1, why: '"Re-" is a prefix and "-ed" is a suffix. The root is "open."' },
        { q: 'Which prefix means "again"?', c: ['un-', 're-', 'dis-', 'mis-'], a: 1, why: '"Re-" means again, like rewrite and reopen.' },
        { q: 'thank + ___ = a word that means "full of thanks"', c: ['-ful', '-ness', '-ly', '-er'], a: 0, why: 'thank + ful = thankful.' },
        { q: 'Which word is an adjective (a describing word)?', c: ['boat', 'jump', 'spicy', 'beam'], a: 2, why: '"Spicy" describes a noun, like spicy soup.' },
        { q: 'Which word is a verb (an action word)?', c: ['basket', 'curtain', 'throw', 'home'], a: 2, why: '"Throw" is something you do.' },
        { q: 'Which word is a proper noun?', c: ['nurse', 'library', 'Denver', 'week'], a: 2, why: 'Proper nouns name a specific place, person or thing, and start with a capital letter: Denver.' },
        { q: 'What two words make the contraction "I\'ve"?', c: ['I have', 'I will', 'I am', 'I had'], a: 0, why: "I've = I have." },
        { q: 'What two words make the contraction "won\'t"?', c: ['will not', 'want not', 'was not', 'would not'], a: 0, why: "Won't is a tricky one: it means will not." },
        { q: 'Vincent took his pet ___ the vet.', c: ['two', 'to', 'too', 'toe'], a: 1, why: '"To" shows direction: to the vet.' },
        { q: '___ going to the museum.', c: ['There', 'Their', "They're", 'Theyre'], a: 2, why: "They're = they are. \"They are going to the museum.\"" },
        { q: '___ house is near the school.', c: ['There', 'Their', "They're", 'Thier'], a: 1, why: '"Their" means it belongs to them.' },
        { q: 'Which word is spelled correctly?', c: ['honist', 'veiw', 'observe', 'wether'], a: 2, why: 'The right spellings are honest, view, observe and weather.' }
      ]
    },
    'j-volume': {
      title: 'Volume & Measurement Check',
      emoji: '🧊',
      note: 'Unit 1: Volume, plus measurement review',
      questions: [
        { q: 'Which is the rule for the volume of a box?', c: ['length + width + height', 'length × width × height', 'length × width', '2 × length + 2 × width'], a: 1, why: 'Volume = length × width × height (or area of the base × height).' },
        { q: 'A box is 7 units long, 4 units wide and 3 units tall. What is its volume?', c: ['14 cubic units', '84 cubic units', '28 cubic units', '74 cubic units'], a: 1, why: '7 × 4 = 28, and 28 × 3 = 84.' },
        { q: 'A box is 5 by 2 by 6. Which expression does NOT show its volume?', c: ['10 × 6', '(5 × 2) × 6', '30 × 2', '(5 × 2) × 2'], a: 3, why: '(5 × 2) × 2 = 20, but the volume is 60. The height 6 is missing!' },
        { q: 'True or false: (5 × 4) × 7 = 5 × (4 × 7)', c: ['True', 'False'], a: 0, why: 'True! You can group factors any way you like: both are 140.' },
        { q: 'True or false: 30 × 50 = 3 × 10 × 5', c: ['True', 'False'], a: 1, why: 'False. 30 × 50 = 1,500 but 3 × 10 × 5 = 150. The 50 is 5 × 10, so a 10 is missing.' },
        { q: 'A cube-shaped container is 7 inches deep. What is its volume?', c: ['21 cubic inches', '49 cubic inches', '343 cubic inches', '147 cubic inches'], a: 2, why: 'A cube has the same length, width and height: 7 × 7 × 7 = 343.' },
        { q: 'How many feet are in 1 yard?', c: ['3', '12', '36', '10'], a: 0, why: '1 yard = 3 feet = 36 inches.' },
        { q: 'Which is the LONGEST?', c: ['4 feet', '1 yard', '38 inches'], a: 0, why: '4 feet = 48 inches, 1 yard = 36 inches. So 4 feet is longest.' },
        { q: 'Which holds the MOST?', c: ['10 pints', '3 quarts', '1 gallon'], a: 0, why: '10 pints = 5 quarts. 1 gallon = 4 quarts. So 10 pints is the most.' },
        { q: 'Which is the SHORTEST?', c: ['1 km', '2,000 m', '100 cm'], a: 2, why: '100 cm = 1 meter, much shorter than 1 km (1,000 m) or 2,000 m.' },
        { q: 'A room is 9 feet wide and twice as long as it is wide. What is the perimeter?', c: ['34 feet', '54 feet', '27 feet', '162 feet'], a: 1, why: 'Length = 18. Perimeter = 18 + 9 + 18 + 9 = 54 feet. Add all four sides!' },
        { q: 'An angle that measures 120° is…', c: ['acute', 'right', 'obtuse', 'straight'], a: 2, why: 'Bigger than 90° but less than 180° is obtuse.' },
        { q: '2/10 + ?/100 = 48/100. What is the missing fraction?', c: ['46/100', '28/100', '2/100', '48/100'], a: 1, why: '2/10 = 20/100. 48 − 20 = 28, so it is 28/100.' }
      ]
    },
    'ca-missions': {
      title: 'California Missions',
      emoji: '⛪',
      note: 'Sample quiz',
      questions: [
        { q: 'What was the first of the California missions, started in 1769?', c: ['Mission San Diego de Alcalá', 'Mission Santa Barbara', 'Mission San Luis Rey', 'Mission Carmel'], a: 0,
          why: 'Mission San Diego de Alcalá was the first California mission, started in 1769.' },
        { q: 'Which Spanish priest started Mission San Diego de Alcalá?', c: ['Juan Cabrillo', 'Father Junípero Serra', 'Hernán Cortés', 'Christopher Columbus'], a: 1,
          why: 'Father Junípero Serra started Mission San Diego and eight more California missions.' },
        { q: 'Which country sent the priests and soldiers who built the missions?', c: ['England', 'France', 'Spain', 'Russia'], a: 2,
          why: 'Spain sent them to claim California and spread its religion.' },
        { q: 'How many missions were built in California?', c: ['7', '13', '21', '50'], a: 2,
          why: 'There were 21 California missions, from San Diego up to Sonoma.' },
        { q: 'What was the road that connected the missions called?', c: ['Route 66', 'El Camino Real', 'The Oregon Trail', 'Main Street'], a: 1,
          why: 'El Camino Real means "The Royal Road." It linked the missions.' },
        { q: 'The missions were mostly built with sun-dried bricks made of mud and straw. What are they called?', c: ['Marble', 'Adobe', 'Glass', 'Steel'], a: 1,
          why: 'Adobe bricks are made of mud and straw dried in the sun.' },
        { q: 'Which Native American people were living in the San Diego area when the mission was built?', c: ['Kumeyaay', 'Navajo', 'Cherokee', 'Iroquois'], a: 0,
          why: 'The Kumeyaay people have lived in the San Diego area for thousands of years.' },
        { q: 'Why did Mission San Diego move in 1774 to its spot in Mission Valley?', c: ['To be near the ocean', 'To be closer to water and good farmland', 'To hide from pirates', 'To be on top of a mountain'], a: 1,
          why: 'The new spot by the San Diego River had more water and better land for farming.' },
        { q: 'In 1775, some Kumeyaay people burned Mission San Diego. What were they fighting against?', c: ['A flood', 'A new school rule', 'The Spanish taking their land and changing their way of life', 'A lost sports game'], a: 2,
          why: 'Many Kumeyaay people resisted the Spanish taking their land and forcing big changes on their lives.' },
        { q: 'Mission San Luis Rey, called the "King of the Missions," is in which San Diego County city?', c: ['Ramona', 'Oceanside', 'Chula Vista', 'Escondido'], a: 1,
          why: 'Mission San Luis Rey de Francia is in Oceanside.' }
      ]
    }
  }
};
