/* ================= Adventure Camp tales =================
   Story bank for crew postcards and the "want to hear about our adventure?" chat when a crew comes home.
   Slots: {K} kid's first name · {t:1-hour|6-hour|overnight} words that fit the trip length · {x} the silly thing without a/an
           · {A} {B} crew pets · {D} place · {P} a camp pal · {F} a camp food · {X} a silly thing · {N} a silly number
   IMPORTANT: only ADD new lines to the END of a list. Saved postcards remember lines by their position. */
window.ADV_TALES={
 open:['Dear {K},','Hi {K}!!!','Dearest {K},','Hello from camp, {K}!','{K}! {K}! Guess what?!','Greetings, {K}!','Yo {K}!','To the one and only {K},','Dear {K} (our favorite human),','Hiya {K}!'],
 sayOpen:['Okay okay okay, {K}, you are NOT going to believe this…','{K}! Sit down. This is a good one.','So there we were in {D}…','Get comfy, {K}. Story time!','Ahem. The Adventures of the Crew, Chapter One…','You want the whole story? Okay, the WHOLE story.','{K}, we have SO much to tell you!','Let me set the scene: {D}. Sunny-ish. Snacks packed.','Promise you won\'t laugh? …Actually, you can laugh.','{t:It all started the second we got there…|It all started at snack time…|It all started at dinner…}','First of all, we missed you. Second of all, LISTEN TO THIS.','Once upon a time… {t:which was about an hour ago…|which was this morning…|which was last night…}'],
 close:['Love,','Hugs and paw prints,','Your adventurous crew,','See you soon!!!','Wish you were here (with snacks),','Your pals forever,','Big squishy hugs,','Missing you already,','Yours truly (and a little sticky),','XOXO,'],
 sayClose:['And that\'s the story! Every word is true. Mostly.','The end! …Can we have a snack now?','And THAT is why we\'re a little sticky.','Anyway, it was the best trip ever. Can we go again?','So yeah. Pretty normal trip.','We\'ll tell you the rest after a nap.','That\'s it! Well, that\'s all we\'re ALLOWED to say.','The end. Clap if you liked it! 👏','And we all lived happily ever after. With snacks.','Worst part of the trip? Leaving. Best part? Coming back to you!','Okay, now YOU tell US what you did!','And that is the true story of our trip. Signed, the crew.'],
 pal:['Gus the camp raccoon','a very chatty frog','Pickles the camp goat','a squirrel named Kevin','Captain Waddles the duck','a snail named Speedy','Barbara the extremely calm cow','a moth who loves the porch light','Sir Hops-a-Lot the bunny','a tiny crab named Pinchy','Doug the confused pigeon','Muffin the camp dog'],
 food:['mystery stew','pancakes shaped like potatoes','green spaghetti','extra-crunchy oatmeal','tuna pudding','pickle pizza','marshmallow soup','burnt toast (the good kind)','jelly beans on toast','sandwiches with no middle','the world\'s longest hot dog','bug-shaped gummies','broccoli ice cream','cheese that squeaks'],
 thing:['a rubber duck','a single flip-flop','a banana peel','a very fancy hat','a kazoo','a squeaky pickle toy','a pinecone','a disco ball','a tiny umbrella','a sparkly sock','a bag of marbles','a traffic cone','a whoopee cushion','a spoon'],
 num:['37','112','a hundred and one','9,000','a bazillion','42','eleventy','573','ninety-nine','a gazillion'],

 /* mini stories: 3 beats each (start, trouble, punchline) */
 plot:[
  ['{t:The minute we got there|First thing|On the first night}, {A} decided to be the camp chef.','{A} made {F}. Nobody knew what was in it. Not even {A}.','{B} ate three bowls and said it was "life-changing". We are worried about {B}.'],
  ['{A} found {X} in the grass and decided it was magic.','{A} carried it everywhere and made wishes on it {t:the whole time|all day|all night}.','One wish came true: we got extra dessert. We are not saying it was magic… but we are not saying it wasn\'t.'],
  ['We had a talent show {t:right before we left|after lunch|around the campfire}.','{A} juggled three pinecones. {B} juggled zero pinecones and a lot of confidence.','{P} won by burping the alphabet. It was not close.'],
  ['{B} wanted to win the "Best Camper" medal SO badly.','{B} made the bed, swept the tent and even brushed {P}.','The medal went to {A} for "{t:Loudest Nap|Most Snores Per Nap|Most Snores Per Night}". {B} is still thinking about it.'],
  ['It rained. A LOT.','Our tent turned into a pool. {A} turned into a pool floatie.','{B} said "at least we don\'t need a bath now." Then it started raining harder.'],
  ['{A} said, "I know a shortcut."','We walked in a circle for {N} minutes and passed the same tree four times.','The tree was nice, though. We named it Gerald.'],
  ['We went fishing!','{A} caught a boot. {B} caught a smaller boot.','{P} caught a fish wearing a tiny boot. So now we have a matching set.'],
  ['{B} tried to learn to whistle.','{t:For a whole hour|All morning|All evening} it was just "pfffft".','{t:Right before we left|At the very end|In the morning}, {B} whistled, a dog came running, and that is how we met {P}.'],
  ['{t:The counselor said, "Nap time!"|The counselor said, "Rest time!"|The counselor said, "Lights out!"}','{A} whispered a joke. {B} giggled. The giggle got louder. And louder.','The counselor laughed so hard she {t:called off nap time|called off rest time|had to turn the lights back on}.'],
  ['We had a pillow fight.','{A} hit {B}. {B} hit {A}. A pillow exploded.','It snowed feathers in the tent. It was honestly beautiful.'],
  ['{A} decided to be brave and do the high dive.','{A} climbed up… looked down… climbed back down… climbed up again…','{A} finally jumped! It was the low dive. We still cheered.'],
  ['We were supposed to make a craft for you.','{A} glued {X} to a paper plate. {B} glued {A} to the table.','Your craft is still drying. {A} is also still drying.'],
  ['{A} made a new friend: {P}.','They did everything together: snacks, naps, more snacks.','When we left, {P} cried. Then {A} cried. Then {B} cried because everyone else was crying.'],
  ['There was a camp scavenger hunt.','The list said: a feather, a red leaf, and {X}.','We somehow found all three. {B} will not tell us where the {X} came from.'],
  ['{A} wrote a song about camp.','The only words were "camp, camp, camp, camp".','{t:Ten minutes later|By lunch|By bedtime} the whole camp was singing it. It is stuck in our heads forever.'],
  ['{t:Snack time|Lunch|Dinner} was {F}.','{t:Second snack|Afternoon snack|Midnight snack} was {F} again, but "with a twist".','The twist was that it was cold. {t:Then we found some cereal|Then we found some cereal|Breakfast was cereal}. Best meal of the trip.'],
  ['{B} lost a tooth! Well, a pretend tooth. {B} made it out of a marshmallow.','{B} put it under the pillow anyway.','{t:After our nap|After our nap|In the morning} there was a coin AND a note that said "nice try". We think it was {P}.'],
  ['We tried to build the tallest tower of rocks ever.','It got taller than {A}! Then taller than {B}!','Then {P} sneezed. We are starting over {t:next trip|next trip|after breakfast}.'],
  ['{A} said, "I bet I can be quiet for a whole {t:ten minutes|hour|hour}."','{A} lasted {t:one minute|four minutes|four minutes}.','Then {A} talked {t:the whole rest of the trip|for the next three hours|for the next three hours} straight to make up for it.'],
  ['{t:We lay in the grass and looked at the clouds.|We lay in the grass and looked at the clouds.|At night we looked at the stars.}','{B} found a {t:cloud|cloud|constellation} shaped like a sandwich.','{A} found one shaped like {B}. {B} says it\'s not a good likeness.'],
  ['We had a sack race!','{A} hopped so fast that {A} hopped right out of the sack.','{A} kept going without it and won. The judges allowed it because it was funny.'],
  ['There was a spooky noise outside the tent: scratch… scratch…','We all hid under one sleeping bag. It was very crowded.','It was {P}, trying to borrow a flashlight. We gave {P} a flashlight AND a snack.'],
  ['{A} tried to teach {P} a math trick.','{A} said, "Pick a number, double it, add ten…"','{P} picked "banana". The math trick did not work.'],
  ['{B} was in charge of the map.','{B} held it upside down {t:the whole time|the whole day|the whole trip}.','We ended up exactly where we wanted to be, so maybe upside down is the right way?'],
  ['We played camp tag.','{A} was "it" for the whole game because nobody could tag anyone back.','{A} finally tagged a tree and declared victory. The tree has not commented.'],
  ['{t:{A} wanted a front-row seat for the camp parade.|{A} wanted a front-row seat for the camp parade.|{A} woke up early to see the sunrise.}','{t:{A} got there first, sat down…|{A} got there first, sat down…|{A} set an alarm, got dressed, sat down…}','{t:…and fell asleep. {A} missed the whole parade. {A} says dreaming about it counts.|…and fell asleep. {A} missed the whole parade. {A} says dreaming about it counts.|…and fell asleep. {A} saw the sunset instead. {A} says it counts.}'],
  ['The camp had a "Crazy Hat {t:Hour|Day|Night}".','{A} wore {X} on their head. {B} wore a whole bush.','A bird moved into {B}\'s hat. {B} won "Best Hat" and also "Best Landlord".'],
  ['{B} said, "Let\'s make s\'mores!"','We had graham crackers and chocolate, but no marshmallows.','So we made "s\'lesses". They were less good. We ate them all anyway.'],
  ['{A} tried to catch a firefly.','The firefly flew away. {A} tried again. And again.','Finally the firefly landed on {A}\'s nose on purpose. We think it felt sorry for {A}.'],
  ['We found a giant puddle.','{A} said "don\'t jump in it". {B} jumped in it.','Then {A} jumped in it too. Then {P}. Now it\'s a much smaller puddle and we are much bigger mud.'],
  ['{A} wanted a pet at camp, so {A} adopted a rock.','The rock got a name (Rocky), a bed (a sock) and a job (paperweight).','Rocky is coming home with us. Please make room.'],
  ['It was SO windy!','{B}\'s hat flew away. Then {B}\'s scarf. Then almost {B}.','We held on to {B} like a kite. It was actually really fun. {B} wants to do it again.']],

 /* mini stories for each place */
 plotAt:{
  meadow:[
   ['We found a hill covered in flowers.','{A} rolled down it. Then {B}. Then {P}.','We came back so covered in petals that the bees thought we were a garden.'],
   ['A butterfly landed on {A}\'s nose.','{A} did not move for {N} minutes so it wouldn\'t fly away.','{A} is now the camp champion of standing still.'],
   ['{B} made a flower crown for everyone.','Then a flower crown for the cows. Then for the fence.','There are no flowers left in the meadow. Oops.'],
   ['We had a picnic in the grass.','Ants carried away one grape. Then another. Then the sandwich.','The ants had a better picnic than us. We clapped for them.'],
   ['{A} found a hole in the ground and said "hello?"','A bunny popped out and said hello back. (Well, it wiggled its nose. Same thing.)','Now {A} and the bunny are pen pals. The bunny is bad at writing.'],
   ['It was the sunniest {t:hour|day|day} ever.','{B} fell asleep in the sun and woke up warm like a cookie.','{A} says {B} smelled like a cookie too. We did not test this.']],
  woods:[
   ['{t:We went on a hike in the dark, dark woods.|We went on a hike in the dark, dark woods.|We went on a night hike in the woods.}','Two big eyes were staring at us from a tree!','It was an owl. It said "hoo". {A} said "me, {A}". They are friends now.'],
   ['{A} followed a trail of acorns.','It went on and on, deeper and deeper…','At the end was a squirrel with a sign that said "Thanks for picking these up".'],
   ['We built a treehouse!','It had a door, a window and a snack shelf.','It was only two feet off the ground but {B} still got scared and climbed down.'],
   ['{B} tried to hug the biggest tree in the woods.','{B} could only reach halfway around.','So {A} and {P} helped, and all three of us hugged it. The tree seemed happy.'],
   ['The woods were super quiet.','Then {A} stepped on a stick. CRACK!','Every bird flew away at once and {B} jumped into {A}\'s arms. {t:We laughed the whole way back.|We laughed for an hour.|We laughed for an hour.}'],
   ['We found a mushroom ring.','{P} said if you stand in it you get a wish.','{A} wished for pancakes. We had pancakes for {t:a snack|lunch|dinner}. Coincidence? We think NOT.']],
  cove:[
   ['{A} built the biggest sandcastle ever.','It had towers, a moat, and a room just for snacks.','Then a wave came. Now it is the biggest sand PANCAKE ever.'],
   ['We went snorkeling!','{B} saw a fish that looked exactly like {A}.','The fish did not think so. It swam away looking insulted.'],
   ['A crab pinched {A}\'s tail.','{A} yelped. The crab yelped. Everyone yelped.','Turns out the crab just wanted a high five. Now they are buddies.'],
   ['We found a message in a bottle!','We opened it very carefully… it said…','"Please return my bottle." So we put it back. Very polite beach.'],
   ['{B} tried surfing.','{B} stood up for one whole second!','Then the wave said "nope". {B} says the wave cheated.'],
   ['The tide went out super far.','We found starfish, shells and {X}.','Nobody knows why {X} was at the beach. The ocean is full of secrets.']],
  caves:[
   ['It was SO dark in the caves.','{A} turned on a flashlight and saw… a face!','It was {A}\'s own reflection in a shiny crystal. {A} screamed at {A}.'],
   ['We heard dripping sounds: drip… drip… drip…','{B} started counting the drips. {B} got to {N}.','Then {B} fell asleep. The drips are still going.'],
   ['{A} found a crystal shaped like a crown.','{A} wore it and said "I am the Cave King!"','A bat flew by and {A} ran away very un-kingly.'],
   ['We found old drawings on the cave wall.','There was a sun, a mammoth, and a stick-person eating a sandwich.','{B} drew a picture of us next to them. Now we are part of history.'],
   ['The echo in the cave was AMAZING.','{A} shouted "{K}!" and the cave shouted it back ten times.','So basically the cave misses you too.'],
   ['We went down a secret tunnel.','It was narrow… then narrower… then SUPER narrow…','{B} got stuck for a minute. We pulled. POP! {B} came out like a cork.']],
  peaks:[
   ['We hiked all the way to the top.','It was so high we were ABOVE the clouds.','{A} tried to jump onto one. We had to hold on to {A}\'s tail. Good call.'],
   ['It snowed on the mountain!','We built a snowpet that looked just like {B}.','The snowpet was better at sitting still than the real {B}.'],
   ['An eagle flew right next to us.','{A} flapped their arms to fly with it.','{A} did not fly. But the eagle did a loop, so we think it was impressed.'],
   ['We had a snowball fight.','{A} threw one at {B}. It missed and hit {P}.','{P} threw one back that was the size of a pumpkin. {P} won.'],
   ['The wind was blowing SO hard at the top.','{B}\'s ears flapped like wings.','{B} lifted a tiny bit off the ground. We are calling it the first flight.'],
   ['We saw a rainbow from above!','It was a full circle up there, not a half.','{A} tried to grab a piece to bring home. Check the sacks!']],
  volcano:[
   ['The volcano rumbled: RUMBLE RUMBLE.','Everyone froze.','It was {A}\'s tummy. {A} missed {t:snack time|lunch|dinner}.'],
   ['It was SO hot at the volcano.','We tried to cook an egg on a rock. It worked!','Then {B} tried to cook pancakes. That did not work. We have a very flat pancake-rock now.'],
   ['We met a baby dragon!','It sneezed and set {A}\'s marshmallow on fire.','{A} said "thanks!" because now it was a perfect s\'more.'],
   ['{B} found a fire pepper and took a big bite.','{B}\'s face went red. Then purple. Then {B} breathed a tiny puff of smoke.','{B} says it was "only a little spicy". {B} drank the whole lake.'],
   ['We walked along the lava river (VERY carefully).','{A} dropped {X} in it.','It went "fssssss" and floated away. RIP, {x}.'],
   ['A dragon took a nap next to our camp.','It snored so loud our tent shook.','But it was nice and warm, so actually it was the best {t:nap|nap|sleep} ever.']],
  harvest:[
   ['We helped make a big feast.','{A} was in charge of the rolls. {A} counted them. Then ate one. Then counted again.','There were fewer rolls than before. Nobody knows why. ({A} knows why.)'],
   ['We raked a HUGE pile of leaves.','{B} jumped in first. Then {A}. Then {P}.','Now there are three leaf monsters and no pile. We have to rake it again.'],
   ['A turkey walked into camp.','It looked at {A}. {A} looked at it. It said "gobble".','{A} said "gobble" back. They talked for an hour. We don\'t know what about.'],
   ['Everyone said one thing they were thankful for.','{A} said friends. {B} said pie.','{P} said "both, but mostly pie". Everyone agreed.']],
  haunt:[
   ['We heard "oooOOOoooo" {t:in the trees|in the trees|in the night}.','We hid under the covers. The "oooOOOooo" came closer…','It was a ghost practicing its singing. It wanted feedback. We said it was great.'],
   ['{A} carved a pumpkin.','It was supposed to be scary. It came out… smiling.','Now it\'s the happiest pumpkin in the whole Hollow. Everyone loves it.'],
   ['A friendly bat moved into our tent.','It hung from the ceiling right above {B}.','{B} tried hanging upside down too. {B} got very dizzy and very giggly.'],
   ['We went trick-or-treating in the Hollow.','A ghost gave us candy. A skeleton gave us candy.','A spider gave us a tiny web. It was the thought that counts.'],
   ['{A} dressed up as a ghost with a sheet.','{A} snuck up on {B} and said "BOO!"','{B} said "hi {A}" because {A}\'s tail was sticking out.'],
   ['The trees in the Hollow have faces.','One of them winked at {A}!','{A} winked back. Now they are best friends. {A} {t:waved goodbye to it ten times|waved goodbye to it ten times|visited it all night}.']]},

 /* single lines anyone can say */
 any:['{A} tried to toast a marshmallow and toasted a pinecone instead. It was crunchy. We do not recommend it.',
  'Camp rule #1: no singing {t:during rest time|during rest time|after bedtime}. {A} sang anyway. The owls joined in. It was actually pretty good.',
  '{A} packed 14 snacks and zero toothbrushes. {B} is not sharing. Please send a toothbrush.',
  'We made friendship bracelets. {A} made one for a rock. The rock seems happy.',
  'At the campfire, {B} told a scary story about a math test with NO answers. Everybody screamed.',
  '{A} lost a sock {t:the minute we got there. We found it ten minutes later|at lunch. We found it at snack time|at dinner. We found it at breakfast}. It was on {B}\'s head. Nobody knows how.',
  'The camp food is okay. {t:Snack one|Lunch|Dinner} was {F}. {t:Snack two|Snack time|Breakfast} was {F}, part two.',
  '{A} and {B} had a staring contest. It lasted {t:15|45|45} minutes. A butterfly landed on {B}\'s nose and {B} lost.',
  'We played hide and seek. {A} is REALLY good at hiding. We did not find {A} until {t:it was time to go home|lunch|dinner}. {A} was behind a tree the whole time.',
  '{B} did a cannonball into the lake. Most of the lake is now on the camp counselor.',
  '{A} snores like a tiny motorboat. {B} snores like a big motorboat. Together they are a boat race.',
  '{P} taught us a secret handshake. It has {N} steps. We remember two of them.',
  'We found {X} under a bush. We don\'t know how it got there. We brought it back to camp anyway.',
  '{B} was voted "Most Likely to Nap". {B} slept through the award.',
  'Our tent is great. It only has one small hole. Okay, three. Okay, it is mostly hole.',
  '{A} learned to paddle a canoe! Mostly in circles. Very fast circles.',
  'The camp has a goat. The goat ate {B}\'s homework. {B} is secretly thrilled.',
  '{A} told {P} a knock-knock joke. {P} is still trying to figure out who\'s there.',
  'We went on a nature walk. {A} named every bug we saw. Most of them are named "Steve".',
  'For arts and crafts we made clay pots. {B}\'s looks like a potato. {B} says it\'s a "potato pot".',
  '{A} brushed teeth with the toothpaste AND the sunscreen. Not at the same time. Well, once.',
  'We had a burping contest. {P} won. Then {P} said "excuse me" very politely. Classy.',
  '{B} got a mosquito bite shaped like a heart. {B} thinks the mosquito loves them.',
  'The water at the lake was SO cold that {A} jumped in and jumped right back out in one move.',
  '{A} ate {N} pancakes at {t:snack time|lunch|breakfast}. We counted. The cook counted too, and looked tired.',
  '{B} made a campfire song up on the spot. It rhymed "pancake" with "earthquake". Genius.',
  'We saw a shooting star! {A} wished for {X}. We don\'t know why.',
  'A frog hopped into our tent and took {B}\'s pillow. We let it. It seemed tired.',
  '{A} wore sunglasses {t:in the shade|in the shade|at night} to look cool. {A} walked into {N} trees. Still looked cool, though.',
  'At the lake, {B} skipped a stone {N} times. (Okay, it was 2. But it FELT like {N}.)',
  '{A} challenged {P} to a race and lost. Then challenged {P} to a nap and won.',
  'Camp {t:snack|lunch|dinner} was {F}. {B} gave it five stars. {A} gave it one star and a sad face.',
  'We made a sign for our tent that says "NO GROWN-UPS". {P} is allowed in because {P} is cool.',
  '{A} practiced cartwheels {t:the whole time|all day|all evening}. {A} can now do half a cartwheel. Which is just falling over, but with style.',
  '{B} found a four-leaf clover and ate it by accident. {B} has been extra lucky ever since. Maybe.',
  'We went on a hayride. {A} got hay in places hay should not be.',
  '{B} wrote "I miss {K}" in the sand. Then a wave came and wrote nothing back. Rude wave.',
  'We learned to tie knots! {A} tied {A}\'s own shoelaces together. It took {t:ten minutes|an hour|an hour} to get untied.',
  'A goose chased {A} across the whole camp. Nobody knows what {A} did. The goose knows.',
  'We played "the floor is lava" for the {t:whole trip|entire day|entire night}. {B} has not touched the floor since {t:we got there|lunch|dinner}.'],

 /* single lines for each place */
 at:{
  meadow:['There are SO many flowers here. {A} sniffed every single one and sneezed {N} times.','A bee followed {B} {t:the whole time|all day|all evening} because {B} smelled like honey. They are best friends now.','{A} tried to count all the clovers. {A} got to 37 and fell asleep in them.','The grass in {D} is so tall that {B} got lost in it twice. We found {B} by the giggling.','We made daisy chains so long they went around the whole camp.','A ladybug rode on {A}\'s head {t:the whole time|all day|all evening} like a tiny red hat.'],
  woods:['A squirrel stole {A}\'s sandwich. {A} stole it back. Then the squirrel\'s cousins showed up. We lost the sandwich.','{B} heard a spooky whisper in the trees. It was {A} whispering "spooky". Classic {A}.','We found a mushroom shaped exactly like {A}\'s face. {A} was NOT amused.','A woodpecker knocked on our tent at 6 AM. We did not let it in.','{A} tried to walk quietly through the woods like a ninja. {A} stepped on every single crunchy leaf.','We saw a deer! It looked at us. We looked at it. Then it left because we were being weird.'],
  cove:['{A} built a sandcastle with a moat, a drawbridge and a snack bar. A crab moved in immediately.','A seagull stole {B}\'s hat. Now the seagull looks very fancy.','{A} found a message in a bottle! It said "please return this bottle". So we did.','{B} got sand EVERYWHERE. We are still finding sand. We will be finding sand forever.','A dolphin splashed {A} on purpose. {A} splashed it back. The dolphin won.','We buried {B} in the sand up to the neck. {B} looked like a sand mermaid. Very majestic.'],
  caves:['It is VERY dark in the caves. {A} said "hello?" and the echo said "hello?" back. {A} said "no, YOU hello." {t:This went on for ten minutes.|This went on for an hour.|This went on for an hour.}','{B} found a shiny crystal and thinks it is a dragon egg. We are keeping it warm just in case.','A bat hung upside down next to {A} {t:the whole time|all afternoon|all night}. {A} tried it too. {A} is now very dizzy.','The caves sparkle when you shine a light. {A} called it "a disco for rocks".','{B} tried to sneak past a sleeping bat. The bat woke up and said nothing. It was very awkward.','We found a crystal that hums. Or maybe that was {A}. It was hard to tell.'],
  peaks:['We climbed so high that {A} stepped on a cloud. It was squishy, like a marshmallow pillow.','{B} tried to high-five an eagle. The eagle left {B} hanging.','The air is thin up here. {A} said everything twice, twice.','{B} yodeled from the top of the mountain. The mountain yodeled back. (It was {P}.)','It is so cold up here that {A}\'s sneeze froze into a tiny snowflake.','We could see the whole world from the top. We waved at your house, {K}!'],
  volcano:['It is SO hot here. {A} made popcorn by holding a kernel up to the lava. POP!','{B} wanted a souvenir rock. It was still warm. {B} is using it as a hand warmer.','We roasted marshmallows on the volcano. {A}\'s marshmallow is now a small black rock. {A} ate it anyway.','A baby dragon hiccuped and made a tiny smoke ring. {B} tried to wear it as a crown.','It is so warm here that we didn\'t need blankets. We used {B} as a pillow instead.','{A} asked the volcano to "please calm down". It rumbled. We left.'],
  harvest:['We had a feast so big that {A} needed a nap halfway through.','{B} made a hat out of a pie tin. It is very shiny and a little bit sticky.','The leaves here are red, orange and gold. {A} tried to collect one of each and ended up with four hundred.'],
  haunt:['A friendly ghost joined our campfire. He was bad at scary stories but GREAT at s\'mores.','{A} dressed up as a ghost and scared {B}. Then a real ghost scared both of them.','The pumpkins here are HUGE. {A} tried to carve one and got stuck inside. We had to roll {A} back to camp.','A skeleton asked to borrow {B}\'s blanket. Skeletons get chilly. They have no… you know… insides.','{A} found a spooky old door. We knocked. A voice said "come back {t:in five minutes|after lunch|after breakfast}".','The owls here say "BOO" instead of "hoo". It took some getting used to.']},

 ps:['P.S. {A} says hi. Actually {A} says "hi hi hi hi hi". {A} had a lot of sugar.','P.S. Please do not tell anyone about the pinecone thing.','P.S. We miss you! But not the homework.','P.S. {B} wants to know if you have been practicing your times tables. (Do it for {B}.)','P.S. Bring more snacks next time. Like, a LOT more.','P.S. We named the camp frog after you. The frog is very proud.',
  'P.S. {P} says hi too. {P} doesn\'t know you, but {P} is very friendly.','P.S. We saved you a piece of {F}. It\'s… changed a little.','P.S. {A} wants you to know {A} was the bravest. {B} wants you to know that is not true.','P.S. Do not look in {B}\'s sack. Trust us.','P.S. {A} learned a new word: "discombobulated". {A} uses it for everything now.','P.S. If you hear a kazoo, it\'s us. Practicing. For you.',
  'P.S. We drew you a picture but {B} used it as a napkin.','P.S. Please do a math problem for us. We miss the sound of your brain working.','P.S. {A} counted the {t:minutes|hours|hours} until we see you. Then counted them again. Then fell asleep.','P.S. Camp is fun, but your house has better snacks.','P.S. {B} says you are the best. {A} says you are the best-est. They are arguing about it.','P.S. Don\'t worry, we are wearing clean socks. Most of us. Some of the time.',
  'P.S. We still have {X}. Do you want it? Please say yes.','P.S. Say hi to everyone at home for us! Especially the snacks.']};
