# 25 new kid-friendly facts (grades 3-5) for review before adding to hn-core.js.
# Each: (topic, emoji, fact, question, right answer, [three wrong answers])
FACTS = [
 ("Faith & holidays", "🤝", "Lebanon officially recognizes 18 different religious communities, including many kinds of Christians and Muslims, the Druze, and a small Jewish community. Families of different faiths live side by side as neighbors.",
  "How many religious communities does Lebanon officially recognize?", "18", ["2", "5", "100"]),
 ("Faith & holidays", "🌸", "March 25 is a national holiday in Lebanon that Christians and Muslims celebrate together. Mary, the mother of Jesus, is honored in both the Bible and the Quran.",
  "Why do Christians and Muslims in Lebanon celebrate March 25 together?", "Mary is honored in both the Bible and the Quran", ["It is the first day of snow", "It is a big soccer game", "It is the cedar tree’s birthday"]),
 ("Faith & holidays", "🎉", "In Lebanon, both Christmas and Eid are public holidays. Lots of kids get days off from school for both!",
  "Which holidays are days off from school in Lebanon?", "Both Christmas and Eid", ["Only Halloween", "Only Thanksgiving", "None at all"]),
 ("Faith & holidays", "🕌", "In downtown Beirut, a big mosque with bright blue domes and a tall church stand right next to each other.",
  "What stands right next to the blue-domed mosque in downtown Beirut?", "A church", ["A volcano", "A pyramid", "A roller coaster"]),
 ("Faith & holidays", "⛰️", "The Qadisha Valley’s name means “Holy Valley.” Long ago, monks built small monasteries right into the sides of its steep cliffs.",
  "Where were the monasteries in the Qadisha Valley built?", "Into the sides of cliffs", ["On boats", "Under the sea", "On top of clouds"]),
 ("Nature & places", "❄️", "The name “Lebanon” comes from an old word that means “white,” because the tops of its mountains are covered in snow.",
  "What does the name “Lebanon” come from?", "A word meaning “white”", ["A word meaning “hot”", "A word meaning “fish”", "A word meaning “pizza”"]),
 ("Nature & places", "🍇", "Between two mountain ranges lies the Beqaa Valley. It is like one giant farm, where grapes, wheat, potatoes and vegetables grow.",
  "What is the Beqaa Valley best known for?", "Farming", ["Skyscrapers", "Volcanoes", "Penguins"]),
 ("Nature & places", "💧", "At Baatara Gorge, a waterfall drops into a deep cave, falling past three natural stone bridges stacked one above the other.",
  "What does the Baatara Gorge waterfall fall past?", "Three natural stone bridges", ["A giant slide", "A train station", "A castle wall"]),
 ("Nature & places", "🪨", "Off the coast of Beirut stand the Pigeon Rocks, two giant rocks in the sea. One has a huge arch that small boats can sail through.",
  "What are Beirut’s Pigeon Rocks?", "Two giant rocks in the sea", ["Rocks shaped like pigeons", "A rock-climbing gym", "A bird zoo"]),
 ("Nature & places", "🫒", "In the village of Bcheale grow some of the oldest olive trees in the world. People call them the “Noah olive trees,” and they are thought to be thousands of years old!",
  "What are the “Noah olive trees” famous for?", "Being thousands of years old", ["Growing chocolate", "Being made of glass", "Walking around at night"]),
 ("Nature & places", "🦅", "Lebanon sits on a giant “bird highway.” Every spring and fall, huge flocks of storks, eagles and other birds fly over Lebanon on their trip between Europe and Africa.",
  "Where are the birds going when they fly over Lebanon?", "Between Europe and Africa", ["To the North Pole", "To the moon", "To Australia"]),
 ("History", "🏰", "As a boy, Moussa dreamed of having his own castle. When he grew up, he built Moussa Castle almost all by himself, stone by stone!",
  "Who built Moussa Castle?", "Mostly one man, by himself", ["Robots", "A big army", "Giants"]),
 ("History", "🏇", "In the city of Tyre you can visit a huge ancient Roman racetrack, where chariots pulled by horses once raced in front of thousands of cheering fans.",
  "What used to race at the ancient track in Tyre?", "Horse-drawn chariots", ["Race cars", "Bicycles", "Snails"]),
 ("History", "⛵", "Phoenician sailors from Tyre crossed the sea and started the famous city of Carthage in North Africa, in what is now Tunisia.",
  "Which famous city did Phoenicians from Tyre start?", "Carthage", ["New York", "London", "Tokyo"]),
 ("Cities", "🍬", "Tripoli is Lebanon’s second-biggest city. It is famous for its sweet shops, full of syrupy pastries and treats.",
  "What is the city of Tripoli famous for?", "Its sweets", ["Its snow", "Its pyramids", "Its rockets"]),
 ("Cities", "🧼", "In Tripoli’s old market there is a place called Khan al-Saboun, the “soap market,” where soap is made by hand from olive oil.",
  "What is the handmade soap in Tripoli made from?", "Olive oil", ["Chocolate", "Sand", "Bubble gum"]),
 ("Family & words", "👵", "Lebanese kids call their grandma “Teta” and their grandpa “Jiddo.”",
  "What does “Teta” mean?", "Grandma", ["Uncle", "Teacher", "Puppy"]),
 ("Family & words", "💛", "“Habibi” (said to a boy) and “Habibti” (said to a girl) mean “my dear.” Lebanese families say it all the time!",
  "What does “habibi” mean?", "My dear", ["Hurry up", "Good night", "I’m hungry"]),
 ("Family & words", "💐", "In Lebanon, Mother’s Day is on March 21, the first day of spring.",
  "When is Mother’s Day in Lebanon?", "March 21, the first day of spring", ["December 25", "July 4", "October 31"]),
 ("Celebrations", "🥁", "At Lebanese weddings, the zaffe is a loud, happy parade of drummers and dancers that leads the bride and groom in.",
  "What is a zaffe?", "A wedding parade with drums and dancing", ["A kind of soup", "A board game", "A sleepy lullaby"]),
 ("Food", "🧀", "Knefeh is a warm, gooey cheese dessert soaked in sweet syrup. Many people eat it for breakfast, tucked inside a sesame bread!",
  "When do many people in Lebanon eat knefeh?", "For breakfast", ["Only on birthdays", "Never, it is just for show", "Only at midnight"]),
 ("Food", "👜", "Ka’ak is a sesame bread shaped like a purse with a handle. Street sellers carry it around the city on carts and bikes.",
  "What shape is ka’ak bread?", "A purse with a handle", ["A star", "A shoe", "A car"]),
 ("Food", "🥗", "Fattoush is a crunchy salad made with crispy pieces of toasted pita bread and a tangy red spice called sumac.",
  "What makes fattoush salad crunchy?", "Crispy pieces of pita bread", ["Ice cubes", "Popcorn", "Crayons"]),
 ("Food", "🍽️", "A Lebanese “mezze” is lots of little dishes, like hummus, salads and dips, placed in the middle of the table for everyone to share.",
  "What is a mezze?", "Lots of small dishes to share", ["One giant cake", "A kind of fork", "A fruit drink"]),
 ("Famous people", "🏥", "Danny Thomas, a famous American actor whose parents came from Lebanon, started St. Jude Children’s Research Hospital to help kids who are very sick.",
  "Which children’s hospital did Danny Thomas start?", "St. Jude Children’s Research Hospital", ["The Moon Hospital", "Hogwarts", "The North Pole Clinic"]),
]
assert len(FACTS) == 25
