# 50 kid-life facts (grades 3-5) for review; keep the approved ones and add them to Q in hn-core.js.
# Each: (topic, fact, question, right answer, [three wrong answers])
FACTS = [
 # ---- Talking like a Lebanese kid
 ("Talk like a Lebanese kid", "To say hello in Arabic, you say “Marhaba!” (mar-ha-ba).",
  "How do you say “hello” in Arabic?", "Marhaba", ["Shukran", "Yalla", "Bonjour"]),
 ("Talk like a Lebanese kid", "Lots of Lebanese people greet each other with “Hi, kifak, ça va?” That is English, Arabic and French, all in one sentence!",
  "What is special about the greeting “Hi, kifak, ça va?”", "It mixes three languages", ["It is a secret code", "It is sung, not said", "It is only for babies"]),
 ("Talk like a Lebanese kid", "“Habibi” (said to a boy) and “Habibti” (said to a girl) mean “my dear.” Families say it all day long!",
  "What does “habibi” mean?", "My dear", ["Hurry up", "Good night", "I’m hungry"]),
 ("Talk like a Lebanese kid", "Lebanese kids call their grandma “Teta” and their grandpa “Jiddo.”",
  "What do Lebanese kids call their grandma?", "Teta", ["Mama Bear", "Nana-Banana", "Jiddo"]),
 ("Talk like a Lebanese kid", "“Yalla!” means “Let’s go!” or “Hurry up!” Lebanese parents say it every morning before school.",
  "What does “Yalla!” mean?", "Let’s go!", ["Be quiet", "Happy birthday", "I’m sleepy"]),
 ("Talk like a Lebanese kid", "The name “Lebanon” comes from an old word that means “white,” because the tops of its mountains are covered in snow.",
  "Where does the name “Lebanon” come from?", "A word meaning “white,” for its snowy mountains", ["A famous king named Leb", "A word meaning “lemon”", "A type of fish"]),
 # ---- School
 ("School", "Many Lebanese schools grade tests out of 20, not 100. Getting 20 out of 20 is a perfect score!",
  "In many Lebanese schools, what is a perfect score on a test?", "20 out of 20", ["100 out of 100", "5 gold stars", "An A+++"]),
 ("School", "Many Lebanese kids learn three languages at school: Arabic, plus French or English, or both!",
  "How many languages do many Lebanese kids learn at school?", "Three", ["One", "Ten", "None"]),
 ("School", "In Lebanon, the biggest meal of the day is lunch, often eaten at home with family after school.",
  "What is the biggest meal of the day in Lebanon?", "Lunch", ["Breakfast", "A midnight snack", "Dessert"]),
 # ---- Food
 ("Food", "A favorite Lebanese breakfast is man’oushe: warm flatbread baked with za’atar (a herb and sesame mix) and olive oil, or with melted cheese.",
  "What do many Lebanese kids eat for breakfast?", "Man’oushe, a warm flatbread", ["Pancakes with syrup", "Cold pizza", "Cereal with chocolate milk"]),
 ("Food", "Labneh is a thick, creamy yogurt spread. A labneh sandwich with cucumbers or olives is a classic school lunch.",
  "What is labneh?", "A thick, creamy yogurt spread", ["A kind of candy", "A soccer team", "A hat"]),
 ("Food", "Knefeh is a favorite Lebanese dessert: warm, gooey melted cheese under a crunchy top, soaked in sweet syrup. Some people eat it for breakfast!",
  "What is inside knefeh?", "Warm, gooey cheese", ["Ice cream", "Peanut butter", "Jelly beans"]),
 ("Food", "Sfouf is a bright yellow cake. Its sunny color comes from a spice called turmeric, not from food coloring.",
  "What makes sfouf cake bright yellow?", "A spice called turmeric", ["Bananas", "Yellow paint", "Lemons"]),
 ("Food", "Tarboosh is a famous Lebanese treat: a fluffy marshmallow on a cookie, dipped in chocolate. It is named after a tall, round hat because that is what it looks like!",
  "Why is the Tarboosh treat called that?", "It looks like a hat called a tarboosh", ["It was invented by a cat", "It tastes like tar", "It is shaped like a boat"]),
 ("Food", "Some brave Lebanese grown-ups eat raw lamb’s liver for breakfast, with mint, garlic and bread. Would you try it?",
  "What do some brave Lebanese grown-ups eat raw for breakfast?", "Lamb’s liver", ["Snails", "Frogs", "Worms"]),
 # ---- Games & sports
 ("Games & sports", "In Lebanon, hide-and-seek is called “ghommayda,” which comes from the word for closing your eyes.",
  "What is “ghommayda”?", "Hide-and-seek", ["Tag", "Jump rope", "A tickle fight"]),
 ("Games & sports", "At Easter, kids dye eggs and have egg battles: two kids tap their eggs together, and whoever’s egg does not crack wins!",
  "How do you win the Easter egg battle?", "Your egg doesn’t crack", ["You eat the most eggs", "You hide the egg best", "You throw it farthest"]),
 ("Games & sports", "Soccer (called “football”) is the most popular sport in Lebanon. Basketball is a big favorite too.",
  "What is the most popular sport in Lebanon?", "Soccer (football)", ["Ice hockey", "Baseball", "Surfing"]),
 ("Games & sports", "Tawleh (backgammon) is a board game with dice. Grandpas teach it to kids, and games get loud with lots of slapping of pieces and friendly teasing!",
  "What is tawleh?", "A board game with dice (backgammon)", ["A kind of bread", "A dance", "A bicycle race"]),
 # ---- Holidays & traditions
 ("Holidays & traditions", "In Lebanon, both Christmas and Eid are public holidays, so lots of kids get days off from school for both!",
  "Which holidays do Lebanese kids get off from school?", "Both Christmas and Eid", ["Only Halloween", "Only Thanksgiving", "None at all"]),
 ("Holidays & traditions", "On Eid, kids visit relatives and often get “eidiyeh”: a gift of money from grown-ups. Cha-ching!",
  "What is “eidiyeh”?", "A money gift for kids on Eid", ["A special Eid hat", "A kind of cookie", "A song"]),
 ("Holidays & traditions", "On December 4 many Lebanese kids celebrate Eid il-Burbara. They dress up in costumes and go house to house, a lot like Halloween! The special treat is boiled wheat with sugar and pomegranate seeds.",
  "Eid il-Burbara is a lot like which holiday?", "Halloween", ["The Fourth of July", "Valentine’s Day", "Groundhog Day"]),
 ("Holidays & traditions", "In Lebanon, Mother’s Day is on March 21, the first day of spring.",
  "When is Mother’s Day in Lebanon?", "March 21, the first day of spring", ["December 25", "July 4", "October 31"]),
 ("Holidays & traditions", "No tooth fairy here! A traditional Arab custom is to throw your baby tooth toward the sun and ask it to swap your tooth for a strong, pretty gazelle’s tooth.",
  "In the old custom, where do kids throw a lost baby tooth?", "Toward the sun", ["Into the ocean", "Under the bed", "Into a cake"]),
 ("Holidays & traditions", "The Arabic birthday song is “Sana helwa ya jamil,” which means “Have a sweet year, beautiful one!”",
  "What does the Arabic birthday song wish you?", "A sweet year", ["A big cake", "Lots of homework", "A long nap"]),
 # ---- Creepy, crawly and wild
 ("Creepy, crawly & wild", "Lebanon has no giant hunting spiders like Australia, but it does have camel spiders. With their legs, they can be bigger than your hand! They are fast and scary-looking, but they are not venomous.",
  "What is true about Lebanon’s camel spiders?", "They can be bigger than your hand but aren’t venomous", ["They ride on camels", "They spin webs as big as houses", "They glow in the dark"]),
 ("Creepy, crawly & wild", "Lebanon’s black tarantula is big enough to catch and eat lizards! Its bite hurts but is not dangerous to people.",
  "What can Lebanon’s black tarantula eat?", "Lizards", ["Cars", "Pizza", "Elephants"]),
 ("Creepy, crawly & wild", "More than 10 kinds of scorpions live in Lebanon. One, the deathstalker, is one of the most venomous scorpions in the world, so people shake out their shoes in dry areas!",
  "Why do some people in Lebanon shake out their shoes?", "To check for scorpions", ["To dry their socks", "To make music", "To find coins"]),
 ("Creepy, crawly & wild", "Striped hyenas live in Lebanon. In snowy winters they sometimes sneak down into villages at night looking for food!",
  "What wild animal sometimes sneaks into Lebanese villages at night?", "A striped hyena", ["A polar bear", "A kangaroo", "A gorilla"]),
 ("Creepy, crawly & wild", "Sea turtles dig nests and lay their eggs on the beaches near the city of Tyre. When the babies hatch, they scurry down the sand into the sea!",
  "What lays eggs on the beaches near Tyre?", "Sea turtles", ["Penguins", "Crocodiles", "Ostriches"]),

 # ---- Everyday life
 ("Everyday life", "Beirut is full of cats! You see them napping on cars, walls and steps all over the city.",
  "Which animal will you see all over the streets of Beirut?", "Cats", ["Kangaroos", "Llamas", "Penguins"]),
 ("Everyday life", "Lebanese drivers honk their horns a LOT: to say hi, to say thanks, or just to say “I’m here!”",
  "Why do Lebanese drivers honk so much?", "To say hi, thanks, or “I’m here!”", ["To play songs", "To scare birds", "Because horns are free on Tuesdays"]),
 ("Everyday life", "At a Lebanese table, a piece of pita bread is often your spoon! You tear off a piece and scoop up hummus and other dips.",
  "What do Lebanese people often use to scoop up hummus?", "A piece of pita bread", ["A straw", "Their elbow", "A tiny shovel"]),
 ("Everyday life", "Sunday lunch at Teta’s house is a big deal. Aunts, uncles and lots of cousins all squeeze around the table together.",
  "Where do many Lebanese families have a big Sunday lunch?", "At Teta’s (Grandma’s) house", ["At the zoo", "On a boat", "At school"]),
 ("Everyday life", "Lebanese kids call grown-up family friends “Amo” (uncle) or “Tante” (aunt), even if they aren’t really related!",
  "What might a Lebanese kid call a grown-up family friend?", "Amo or Tante (uncle or aunt)", ["Captain", "Your Majesty", "Buddy-Pal"]),
 ("Everyday life", "Many Lebanese people greet friends and family with three kisses on the cheeks: right, left, right!",
  "How many cheek kisses are in a classic Lebanese hello?", "Three", ["Zero", "Ten", "Twenty"]),
 ("Everyday life", "If you ask a Lebanese parent for a treat, they might say “Inshallah,” which means “if God wills.” Kids know it often means “maybe!”",
  "When a Lebanese parent answers “Inshallah,” what does it often mean?", "Maybe!", ["Yes, right now!", "Go to bed", "Do your homework"]),
 # ---- Food & treats
 ("Food & treats", "Lebanese pickled turnips are bright pink! They get their color from a slice of beet in the jar.",
  "What makes Lebanese pickled turnips pink?", "A slice of beet", ["Pink paint", "Strawberry jam", "Bubble gum"]),
 ("Food & treats", "In Lebanon, a “cocktail” is a thick fruit smoothie in a cup, piled with fruit chunks, sweet cream called ashta, honey and nuts. You eat it with a spoon!",
  "What is a Lebanese fruit “cocktail”?", "A thick fruit smoothie topped with cream, honey and nuts", ["A soda with ice", "A chicken dish", "A kind of hat"]),
 ("Food & treats", "Many Lebanese desserts are flavored with rose water or orange blossom water, so they taste a little like flowers!",
  "Many Lebanese sweets taste a little like…", "Flowers", ["Pickles", "Toothpaste", "Pepperoni"]),
 ("Food & treats", "In spring, kids snack on janarek: small, sour green plums dipped in salt. Crunchy and super sour!",
  "How do Lebanese kids like to eat sour green plums?", "Dipped in salt", ["Dipped in ketchup", "Frozen in ice", "Covered in sprinkles"]),
 ("Food & treats", "Kibbeh nayyeh is a Lebanese dish of finely ground meat that is eaten RAW, with olive oil, mint and onions. Gross or yum?",
  "What is special about kibbeh nayyeh?", "The meat is eaten raw", ["It is frozen solid", "It is bright blue", "It is made of candy"]),
 # ---- Words & letters
 ("Words & letters", "Arabic is written from right to left, but numbers are written from left to right, just like in English!",
  "Which way are numbers written in Arabic?", "Left to right", ["Right to left", "Top to bottom", "In a circle"]),
 ("Words & letters", "The Arabic alphabet has 28 letters. Most letters change their shape depending on whether they are at the start, middle or end of a word.",
  "How many letters are in the Arabic alphabet?", "28", ["10", "26", "100"]),
 # ---- Holidays
 ("Holidays & traditions", "In Lebanon, Santa Claus is called “Baba Noël.”",
  "What do Lebanese kids call Santa Claus?", "Baba Noël", ["Mr. Snowman", "Jiddo Frost", "Captain Christmas"]),
 ("Holidays & traditions", "During Ramadan, a drummer called the musaharati walks the streets before sunrise, drumming and singing to wake families up for their early meal.",
  "What does the musaharati do during Ramadan?", "Drums in the streets to wake people for an early meal", ["Bakes all the bread", "Paints the houses", "Delivers the mail"]),
 # ---- Creepy, crawly & wild (more)
 ("Creepy, crawly & wild", "Chameleons live in Lebanon. They can change color, and their eyes can look in two different directions at once!",
  "What can Lebanon’s chameleons do?", "Change color and look two ways at once", ["Fly", "Talk", "Breathe fire"]),
 ("Creepy, crawly & wild", "Wolves still live in the mountains of Lebanon, along with foxes, jackals and wild boars.",
  "Which wild animal still lives in Lebanon’s mountains?", "Wolves", ["Tigers", "Pandas", "Zebras"]),
 ("Creepy, crawly & wild", "In summer, huge groups of jellyfish sometimes float along Lebanon’s beaches. Their sting hurts, so swimmers watch out!",
  "What do swimmers in Lebanon watch out for in summer?", "Stinging jellyfish", ["Sharks with hats", "Flying fish that bite", "Hot lava"]),
 # ---- History (kid-sized)
 ("History", "In the 1960s, a teacher and his college students in Lebanon built and launched their own rockets, called Cedar rockets. Some flew more than 10 miles high!",
  "What did college students in Lebanon build in the 1960s?", "Rockets", ["A robot dog", "The first video game", "A submarine"]),
]
assert len(FACTS) == 50, len(FACTS)
